// Usage-oriented labels for the exact Pokémon Black/White SDAT sequence symbols.
// Folder/UI names describe in-game use rather than soundtrack titles.
// Internal names are still written into each exported info.txt.
export const SONG_USAGE = {
  "SEQ_BGM_STARTING": "New Game introduction - Part 1",
  "SEQ_BGM_STARTING2": "New Game introduction - Part 2",
  "SEQ_BGM_E_OPENING": "Opening story scene",
  "SEQ_BGM_T_01": "Nuvema Town",
  "SEQ_BGM_VS_RIVAL": "Battle! (Cheren/Bianca)",
  "SEQ_BGM_E_TSURETEKE1": "Story escort / follow scene - Part 1",
  "SEQ_BGM_E_DOCTOR": "Professor Juniper scenes",
  "SEQ_BGM_LABO": "Juniper Pokémon Lab",
  "SEQ_ME_KEYITEM": "Obtained a Key Item!",
  "SEQ_BGM_E_FRIEND": "Traveling together event",
  "SEQ_BGM_R_A": "Route 1",
  "SEQ_BGM_VS_NORAPOKE": "Battle! (Wild Pokémon)",
  "SEQ_BGM_WIN1": "Victory! (Wild Pokémon)",
  "SEQ_ME_LVUP": "Level Up!",
  "SEQ_BGM_T_02": "Accumula Town",
  "SEQ_BGM_E_TSURETEKE2": "Story escort / follow scene - Part 2",
  "SEQ_BGM_POKECEN": "Pokémon Center",
  "SEQ_ME_ASA": "Pokémon Healed",
  "SEQ_ME_HYOUKA1": "Pokédex Evaluation... You've Just Begun!",
  "SEQ_BGM_E_SAGE": "Seven Sages / Team Plasma story scene",
  "SEQ_BGM_R_B_SP": "Route 2 (Spring)",
  "SEQ_BGM_R_B_SU": "Route 2 (Summer)",
  "SEQ_BGM_R_B_AU": "Route 2 (Autumn)",
  "SEQ_BGM_R_B_WI": "Route 2 (Winter)",
  "SEQ_ME_CALL": "Xtransceiver",
  "SEQ_BGM_EYE_01": "Trainers' Eyes Meet (Youngster)",
  "SEQ_BGM_VS_TRAINER": "Battle! (Trainer Battle)",
  "SEQ_BGM_WIN2": "Victory! (Trainer Battle)",
  "SEQ_BGM_EYE_02": "Trainers' Eyes Meet (Lass)",
  "SEQ_ME_ITEM": "Obtained an Item!",
  "SEQ_BGM_C_01": "Striaton City",
  "SEQ_ME_HYOUKA2": "Pokédex Evaluation... You're on Your Way!",
  "SEQ_BGM_D_01": "The Dreamyard",
  "SEQ_BGM_D_01_B1F": "The Dreamyard (B1F)",
  "SEQ_BGM_E_PLASMA": "Team Plasma encounter scenes",
  "SEQ_BGM_VS_PLASMA": "Battle! (Team Plasma)",
  "SEQ_BGM_WIN6": "Victory! (Team Plasma)",
  "SEQ_BGM_SHINKA": "Evolution sequence - Part 1",
  "SEQ_BGM_KOUKAN": "Evolution sequence - Part 2",
  "SEQ_ME_SHINKAOME": "Congratulations! Your Pokémon Evolved!",
  "SEQ_BGM_EYE_03": "Trainers' Eyes Meet (Twins)",
  "SEQ_BGM_E_RIVAL": "Cheren scenes",
  "SEQ_BGM_E_TROUBLE": "Urgent / trouble story scenes",
  "SEQ_BGM_C_02": "Nacrene City",
  "SEQ_ME_HYOUKA3": "Pokédex Evaluation... Keep at It!",
  "SEQ_BGM_GYM": "Pokémon Gym",
  "SEQ_BGM_VS_GYMLEADER": "Battle! (Gym Leader)",
  "SEQ_BGM_BATTLESUPERIOR": "Gym Leader battle - final Pokémon",
  "SEQ_BGM_WIN3": "Victory! (Gym Leader)",
  "SEQ_ME_BADGE": "Received a League Gym Badge",
  "SEQ_ME_WAZA": "Obtained a TM!",
  "SEQ_BGM_GATE": "Gate",
  "SEQ_BGM_H_01": "Skyarrow Bridge",
  "SEQ_BGM_C_03": "Castelia City",
  "SEQ_BGM_EYE_12": "Trainers' Eyes Meet (Clerk ♂)",
  "SEQ_BGM_R_C_SP": "Route 4 (Spring)",
  "SEQ_BGM_R_C_SU": "Route 4 (Summer)",
  "SEQ_BGM_R_C_AU": "Route 4 (Autumn)",
  "SEQ_BGM_R_C_WI": "Route 4 (Winter)",
  "SEQ_BGM_EYE_11": "Trainers' Eyes Meet (Backpacker)",
  "SEQ_BGM_C_04": "Nimbasa City",
  "SEQ_BGM_E_SUPPORT": "Bianca scenes",
  "SEQ_BGM_E_EMOTION": "Emotional story scenes",
  "SEQ_BGM_E_N": "N scenes",
  "SEQ_BGM_VS_N": "Battle! (N)",
  "SEQ_BGM_BATTLEPINCH": "Battle - low HP",
  "SEQ_BGM_BICYCLE": "Bicycle",
  "SEQ_BGM_E_CHAMPION": "Alder scenes",
  "SEQ_BGM_H_02": "Driftveil Drawbridge",
  "SEQ_BGM_C_05": "Driftveil City",
  "SEQ_BGM_D_03": "Cold Storage",
  "SEQ_BGM_R_D_SP": "Route 6 (Spring)",
  "SEQ_BGM_R_D_SU": "Route 6 (Summer)",
  "SEQ_BGM_R_D_AU": "Route 6 (Autumn)",
  "SEQ_BGM_R_D_WI": "Route 6 (Winter)",
  "SEQ_BGM_EYE_06": "Trainers' Eyes Meet (Parasol Lady)",
  "SEQ_BGM_EYE_09": "Trainers' Eyes Meet (Scientist)",
  "SEQ_BGM_D_02": "Chargestone Cave",
  "SEQ_BGM_D_02_B1F": "Chargestone Cave (B1F)",
  "SEQ_BGM_D_02_B2F": "Chargestone Cave (B2F)",
  "SEQ_BGM_C_06": "Mistralton City",
  "SEQ_BGM_E_DOCTOR2": "Cedric Juniper scenes",
  "SEQ_ME_HYOUKA4": "Pokédex Evaluation... Not Bad!",
  "SEQ_ME_WASURE": "Move Deleted",
  "SEQ_BGM_EYE_08": "Trainers' Eyes Meet (Psychic)",
  "SEQ_BGM_C_07": "Icirrus City",
  "SEQ_BGM_D_05": "Dragonspiral Tower",
  "SEQ_BGM_EYE_PLASMA": "Trainers' Eyes Meet (Team Plasma)",
  "SEQ_BGM_D_07": "Dragonspiral Tower Top Floor",
  "SEQ_BGM_D_04": "Relic Castle",
  "SEQ_ME_ITEM_MYSTERY": "Light Stone/Dark Stone",
  "SEQ_BGM_H_03": "Tubeline Bridge",
  "SEQ_BGM_FS": "Shopping Mall Nine",
  "SEQ_BGM_EYE_05": "Trainers' Eyes Meet (Roughneck)",
  "SEQ_BGM_C_08_B": "Opelucid City (Pokémon Black)",
  "SEQ_BGM_C_08_W": "Opelucid City (Pokémon White)",
  "SEQ_BGM_R_F": "Route 10",
  "SEQ_BGM_D_CHAMPROAD": "Victory Road (All Badges)",
  "SEQ_BGM_EYE_04": "Trainers' Eyes Meet (Ace Trainer)",
  "SEQ_BGM_POKEMON_LEAGUE": "The Pokémon League",
  "SEQ_BGM_VS_SHITENNO": "Battle! (Elite Four)",
  "SEQ_BGM_E_N_CASTLE": "N's Castle rises at the Pokémon League",
  "SEQ_BGM_N_CASTLE_BRIDGE": "N's Castle bridge",
  "SEQ_BGM_N_CASTLE": "N's Castle",
  "SEQ_BGM_N_ROOM": "N's room",
  "SEQ_BGM_E_LEGEND_COME": "N's Dragon",
  "SEQ_BGM_E_LEGEND_BORN": "The Dragon Awakes",
  "SEQ_BGM_VS_SHIN": "Battle! (Reshiram/Zekrom)",
  "SEQ_BGM_VS_N_2": "Decisive Battle! (N)",
  "SEQ_BGM_E_G_CIS": "Ghetsis scenes",
  "SEQ_BGM_VS_G_CIS": "Battle! (Ghetsis)",
  "SEQ_BGM_E_LAST": "Final farewell scene",
  "SEQ_BGM_ENDING": "Ending credits",
  "SEQ_BGM_E_HANDSOME": "Looker scenes",
  "SEQ_ME_TAMAGO_GET": "Received a Pokémon Egg!",
  "SEQ_BGM_PLEASURE_BOAT": "The Royal Unova",
  "SEQ_BGM_WIFI_ACCESS": "Nintendo Wi-Fi Connection",
  "SEQ_BGM_GLTERMINAL": "Global Terminal",
  "SEQ_BGM_GTS": "Gts",
  "SEQ_BGM_GURUGURU": "Spin Trade",
  "SEQ_BGM_UNITED_NATIONS": "Unity Tower",
  "SEQ_ME_HYOUKA5": "Pokédex Evaluation... Just a Little More!",
  "SEQ_BGM_GEAR_STATION": "Gear Station",
  "SEQ_BGM_BATTLE_SUBWAY": "The Battle Subway (Carriage 7)",
  "SEQ_BGM_VS_SUBWAY_TRAINER": "Battle! (Battle Subway Trainer)",
  "SEQ_ME_BPGET": "Received BP!",
  "SEQ_BGM_MSL_FIELD": "Pokémon Musical Theater",
  "SEQ_ME_ACCE": "Received Props!",
  "SEQ_BGM_MSL_DRESSUP": "Pokémon Musical - dress-up",
  "SEQ_BGM_MSL_BEFORE": "Pokémon Musical - before the performance",
  "SEQ_BGM_MSL_01": "Pokémon Musical performance - Stardom",
  "SEQ_BGM_MSL_02": "Pokémon Musical performance - Forest Stroll",
  "SEQ_BGM_MSL_03": "Pokémon Musical performance - A Sweet Soirée",
  "SEQ_BGM_MSL_04": "Pokémon Musical performance - Exciting Nimbasa",
  "SEQ_BGM_MSL_DL_MUNNA": "Musical: \"Charming Munna\"",
  "SEQ_BGM_MSL_DL_SMASH": "Musical: \"Pokémon Smash!\"",
  "SEQ_BGM_MSL_DL_FESTA": "Musical: \"Carnival Pokémon\"",
  "SEQ_BGM_MSL_DL_RELIC": "Musical: \"Meloettaaa!!!\"",
  "SEQ_BGM_MSL_DL_RUNPA": "Musical: \"Carnival Ludicolo!\"",
  "SEQ_BGM_E_KANRANSYA": "Nimbasa Ferris wheel ride",
  "SEQ_ME_AISHOU_KIDOU": "Feeling Check",
  "SEQ_ME_AISHOU_H": "Feeling Check: Perfect!",
  "SEQ_ME_AISHOU_M": "Feeling Check: Getting Close",
  "SEQ_ME_AISHOU_L": "Feeling Check: Lukewarm",
  "SEQ_BGM_VS_MOVEPOKE": "Battle - roaming legendary Pokémon",
  "SEQ_BGM_T_03": "Anville Town",
  "SEQ_BGM_H_05": "Marvelous Bridge",
  "SEQ_BGM_R_E_SP": "Route 12 (Spring)",
  "SEQ_BGM_R_E_SU": "Route 12 (Summer)",
  "SEQ_BGM_R_E_AU": "Route 12 (Autumn)",
  "SEQ_BGM_R_E_WI": "Route 12 (Winter)",
  "SEQ_BGM_EYE_07": "Trainers' Eyes Meet (Cyclist)",
  "SEQ_BGM_PALPARK": "Poké Transfer Lab",
  "SEQ_BGM_PALPARK_BOX": "Poké Transfer: Choose Your Pokémon!",
  "SEQ_BGM_PALPARK_GAME": "Poké Transfer: Catch Your Pokémon!",
  "SEQ_BGM_EYE_10": "Trainers' Eyes Meet (Pokéfan)",
  "SEQ_BGM_C_10_B": "Black City",
  "SEQ_BGM_C_10_W": "White Forest",
  "SEQ_BGM_GAME_SYNC": "Game Sync",
  "SEQ_BGM_PALACE": "Entralink",
  "SEQ_ME_MISSION_START": "Begin an Entralink Mission!",
  "SEQ_BGM_PALACE2": "Someone's Entralink",
  "SEQ_ME_MISSION_CLEAR": "Mission Accomplished!",
  "SEQ_ME_MISSION_FAILED": "Mission Failed!",
  "SEQ_BGM_EYE_13": "Trainers' Eyes Meet (Gentleman)",
  "SEQ_BGM_T_05_SP": "Undella Town (Spring)",
  "SEQ_BGM_T_05_SU": "Undella Town (Summer)",
  "SEQ_BGM_E_SHIRONA": "Cynthia scenes",
  "SEQ_BGM_VS_SHIRONA": "Battle! (Cynthia)",
  "SEQ_BGM_D_06": "Lostlorn Forest",
  "SEQ_BGM_VS_TSUYOPOKE": "Battle! (Strong Wild Pokémon)",
  "SEQ_BGM_NAMINORI": "Surf",
  "SEQ_BGM_DIVING": "Abyssal Ruins",
  "SEQ_BGM_T_04": "Lacunosa Town",
  "SEQ_BGM_H_04": "Village Bridge",
  "SEQ_BGM_WIFI_PRESENT": "Mystery Gift",
  "SEQ_BGM_WCS": "Battle Competition screen",
  "SEQ_BGM_E_SOUND_DESIGNER": "Game Freak sound designer / Team Rocket easter egg event",
  "SEQ_BGM_VS_RAI": "Battle! (Kyurem)",
  "SEQ_ME_HYOUKA6": "Pokédex Evaluation... It's Perfect!",
  "SEQ_BGM_VS_CHAMP": "Battle! (Champion)",
  "SEQ_BGM_WIN5": "Victory! (Champion)",
  "SEQ_BGM_E_DENDOUIRI": "Hall of Fame entry",
  "SEQ_BGM_E_INISHIE": "Meloetta / Relic Song event",
  "SEQ_BGM_VS_WCS": "Pokémon World Championships Final",
  "SEQ_ME_KINOMI": "Obtained a Berry! (Unused)",
  "SEQ_BGM_GF_LOGO": "Game Freak logo",
  "SEQ_BGM_TITLE": "Opening cinematic - N's coronation",
  "SEQ_BGM_TITLE01": "Opening cinematic - second cue",
  "SEQ_BGM_POKEMON_THEME": "Title screen",
  "SEQ_BGM_DUMMY": "Unused / dummy music sequence",
  "SEQ_BGM_SILENCE_FIELD": "Field silence",
  "SEQ_BGM_SILENCE_DUNGEON": "Dungeon silence",
  "SEQ_BGM_OPENING_TITLE_B": "Opening title transition (Pokémon Black)",
  "SEQ_BGM_OPENING_TITLE_W": "Opening title transition (Pokémon White)",
  "SEQ_BGM_ENDING2": "Ending transition (silent)",
  "SEQ_BGM_T_05_AU": "Undella Town (Autumn)",
  "SEQ_BGM_T_05_WI": "Undella Town (Winter)",
  "SEQ_BGM_GYM_C05": "Driftveil Gym",
  "SEQ_BGM_POKEMON_LEAGUE2": "Pokémon League - alternate state",
  "SEQ_BGM_E_GL_UNION": "Online / Global Link story event",
  "SEQ_BGM_E_LEGEND_BORN_B": "Legendary dragon awakening cutscene (Pokémon Black)",
  "SEQ_BGM_E_LEGEND_BORN_W": "Legendary dragon awakening cutscene (Pokémon White)",
  "SEQ_BGM_VS_MU": "Battle - special legendary Pokémon variant",
  "SEQ_BGM_VS_SETPOKE": "Battle - stationary legendary Pokémon",
  "SEQ_BGM_WIN4": "Victory - Elite Four",
  "SEQ_BGM_VS_TRAINER_M": "Trainer battle - multiplayer variant M",
  "SEQ_BGM_VS_TRAINER_S": "Trainer battle - multiplayer variant S",
  "SEQ_BGM_E_LEGEND_COME_B": "N's legendary dragon appearance cutscene (Pokémon Black)",
  "SEQ_BGM_E_LEGEND_COME_W": "N's legendary dragon appearance cutscene (Pokémon White)",
  "SEQ_BGM_VS_TRAINER_WIFI": "Trainer battle - Wi-Fi",
  "SEQ_BGM_E_EPIROGUE": "Postgame epilogue cutscene (Pokémon Black)",
  "SEQ_BGM_E_EPIROGUE_W": "Postgame epilogue cutscene (Pokémon White)",
  "SEQ_BGM_MSL_DL_01": "Pokémon Musical - downloadable slot 1 placeholder",
  "SEQ_BGM_MSL_DL_02": "Pokémon Musical - downloadable slot 2 placeholder",
  "SEQ_BGM_MSL_DL_03": "Pokémon Musical - downloadable slot 3 placeholder",
  "SEQ_BGM_MSL_DL_04": "Pokémon Musical - downloadable slot 4 placeholder",
  "SEQ_BGM_END": "Unused / end marker music sequence"
};
