// Pokémon Black/White SWAR/SWAV instrument labels.
// Generated from the user-provided "Pokémon Sound Sources (Detailed)" BW sheet.
// Only the Sample Description column is included; source-library provenance is intentionally omitted.
export const BW_SWAV_LABELS = {
  "WAVE_MUS_WB_TITLE": {
    "0": "Solo Cello",
    "1": "Female Choir",
    "2": "Female Choir",
    "3": "Female Choir",
    "4": "Male Choir",
    "5": "Male Choir",
    "6": "Male Choir",
    "7": "Suspended Cymbal",
    "8": "Orchestral Cymbal",
    "9": "Gong",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Orchestral Snare",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "Timpani",
    "19": "Timpani",
    "20": "Timpani",
    "21": "Tubular Bells"
  },
  "WAVE_MUS_WB_TITLE01": {
    "0": "Solo Cello",
    "1": "Orchestral Cymbal",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Trombone Stab",
    "6": "Flute",
    "7": "Flute",
    "8": "Flute",
    "9": "Flute",
    "10": "Orchestral Snare",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "Timpani",
    "16": "Timpani",
    "17": "Trombone Ensemble",
    "18": "Trombone Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_POKEMON_THEME": {
    "0": "Upright Bass",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Trumpet Ensemble",
    "4": "Solo Cello",
    "5": "Suspended Cymbal",
    "6": "Orchestral Cymbal",
    "7": "Flute",
    "8": "Flute",
    "9": "French Horn Ensemble",
    "10": "French Horn Ensemble",
    "11": "Glockenspiel",
    "12": "Trombone Stab",
    "13": "Oboe",
    "14": "Oboe",
    "15": "Solo Trumpet",
    "16": "Reverse Cymbal",
    "17": "Drum Roll",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "Timpani",
    "23": "Trombone Ensemble",
    "24": "Trombone Ensemble",
    "25": "Tubular Bells"
  },
  "WAVE_MUS_WB_STARTING": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Flute",
    "6": "Flute",
    "7": "Flute",
    "8": "Reverse Cymbal",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Timpani",
    "15": "Trombone Ensemble",
    "16": "Trombone Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_SHINKA": {
    "0": "Celesta"
  },
  "WAVE_MUS_WB_KOUKAN": {
    "0": "Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Marschall Guitar",
    "6": "Marschall Guitar",
    "7": "Marschall Guitar",
    "8": "Closed HiHat",
    "9": "Open HiHat",
    "10": "Power Snare",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Synth Bass",
    "14": "Timpani",
    "15": "Timpani",
    "16": "Low Floor Tom",
    "17": "High Rack Tom",
    "18": "High Floor Tom",
    "19": "Low Rack Tom"
  },
  "WAVE_MUS_WB_BICYCLE": {
    "0": "Crash Cymbal",
    "1": "Rhode Piano",
    "2": "Rhode Piano",
    "3": "Clap",
    "4": "Closed HiHat",
    "5": "Open HiHat",
    "6": "Kick",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Flute",
    "12": "Flute",
    "13": "Flute",
    "14": "Flute",
    "15": "Power Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "Synth Bass",
    "21": "Triangle"
  },
  "WAVE_MUS_WB_NAMINORI": {
    "0": "Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "French Horn",
    "4": "French Horn",
    "5": "French Horn",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Harp",
    "10": "Harp",
    "11": "Harp",
    "12": "Closed HiHat",
    "13": "Open HiHat",
    "14": "Power Snare",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Synth Bass",
    "20": "Synth Bass",
    "21": "Low Floor Tom",
    "22": "High Rack Tom",
    "23": "High Floor Tom",
    "24": "Low Rack Tom",
    "25": "Trumpet Ensemble",
    "26": "Trumpet Ensemble",
    "27": "Trumpet Ensemble",
    "28": "Vibraphone",
    "29": "Vibraphone"
  },
  "WAVE_MUS_WB_DIVING": {
    "0": "High Bongo",
    "1": "Drawbar Organ",
    "2": "Drawbar Organ",
    "3": "Drawbar Organ",
    "4": "Rhode Piano",
    "5": "Rhode Piano",
    "6": "Open High Conga",
    "7": "Muted Conga",
    "8": "Reverse Cymbal",
    "9": "Low Underwater SFX",
    "10": "Mid Underwater SFX",
    "11": "More Underwater SFX",
    "12": "More Underwater SFX",
    "13": "More Underwater SFX",
    "14": "Sitar",
    "15": "Sitar",
    "16": "Sitar",
    "17": "Sitar",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "Triangle"
  },
  "WAVE_MUS_WB_E_DENDOUIRI": {
    "0": "Crash Cymbal",
    "1": "Rhode Piano",
    "2": "Rhode Piano",
    "3": "Resonant Synth",
    "4": "Resonant Synth",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Closed HiHat",
    "10": "Open HiHat",
    "11": "Kick",
    "12": "Drum Loop",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "Synth Bass",
    "17": "Synth Bass",
    "18": "Vibraphone",
    "19": "Vibraphone",
    "20": "Vibraphone"
  },
  "WAVE_MUS_WB_ENDING": {
    "0": "Solo Cello",
    "1": "Chinese Cymbal",
    "2": "Choir Aahs",
    "3": "Choir Aahs",
    "4": "Choir Aahs",
    "5": "Pipe Organ",
    "6": "Pipe Organ",
    "7": "Pipe Organ",
    "8": "Crash Cymbal",
    "9": "Suspended Cymbal",
    "10": "Orchestral Cymbal",
    "11": "Marschall Guitar",
    "12": "French Horn Ensemble",
    "13": "French Horn Ensemble",
    "14": "French Horn Ensemble",
    "15": "Closed HiHat",
    "16": "Open HiHat",
    "17": "Kick",
    "18": "Orchestral Snare",
    "19": "Power Snare",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "Synth Bass",
    "25": "Timpani",
    "26": "Low Floor Tom",
    "27": "High Floor Tom",
    "28": "Low Rack Tom",
    "29": "Tubular Bells"
  },
  "WAVE_MUS_WB_T_01": {
    "0": "Accordion",
    "1": "Accordion",
    "2": "Accordion",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Fretless Bass",
    "7": "Flute",
    "8": "Flute",
    "9": "Flute",
    "10": "Flute",
    "11": "French Horn Ensemble",
    "12": "French Horn Ensemble",
    "13": "French Horn Ensemble",
    "14": "French Horn Ensemble",
    "15": "Harpsichord",
    "16": "Harpsichord",
    "17": "Harpsichord",
    "18": "Harpsichord",
    "19": "Nylon String Guitar",
    "20": "Nylon String Guitar",
    "21": "Nylon String Guitar"
  },
  "WAVE_MUS_WB_T_02": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Crash Cymbal",
    "4": "Flute",
    "5": "Flute",
    "6": "Flute",
    "7": "Flute",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Claps",
    "13": "Closed HiHat",
    "14": "Open HiHat",
    "15": "Kick",
    "16": "Nylon String Guitar",
    "17": "Nylon String Guitar",
    "18": "Nylon String Guitar",
    "19": "Orchestral Snare",
    "20": "Tom",
    "21": "Solo Violin",
    "22": "Solo Violin",
    "23": "Solo Violin"
  },
  "WAVE_MUS_WB_T_03": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Flute",
    "3": "Flute",
    "4": "Flute",
    "5": "Flute",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Nylon String Guitar",
    "15": "Nylon String Guitar",
    "16": "Nylon String Guitar",
    "17": "Nylon String Guitar",
    "18": "Pizzicato String Ensemble",
    "19": "Pizzicato String Ensemble",
    "20": "Pizzicato String Ensemble",
    "21": "Pizzicato String Ensemble",
    "22": "Pizzicato String Ensemble",
    "23": "Analog Snare",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "String Ensemble",
    "27": "String Ensemble"
  },
  "WAVE_MUS_WB_T_04": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Open High Conga",
    "12": "Kick",
    "13": "Nylon String Guitar",
    "14": "Nylon String Guitar",
    "15": "Nylon String Guitar",
    "16": "Rim Hit",
    "17": "Shaker",
    "18": "Vibraphone",
    "19": "Vibraphone",
    "20": "Vibraphone"
  },
  "WAVE_MUS_WB_T_05_SP": {
    "0": "Rhode Piano",
    "1": "Rhode Piano",
    "2": "Ocean Waves SFX",
    "3": "String Ensemble",
    "4": "String Ensemble",
    "5": "String Ensemble",
    "6": "String Ensemble",
    "7": "Celesta"
  },
  "WAVE_MUS_WB_T_05_SU": {
    "0": "Kick",
    "1": "Clean Guitar",
    "2": "Clean Guitar",
    "3": "Clean Guitar",
    "4": "Crash Cymbal",
    "5": "Fretless Bass",
    "6": "Fretless Bass",
    "7": "Open High Conga",
    "8": "Ocean Waves SFX",
    "9": "Side Stick",
    "10": "Rim Hit",
    "11": "Shaker",
    "12": "Power Snare",
    "13": "Steel Drum",
    "14": "Steel Drum",
    "15": "Steel Drum",
    "16": "Floor Tom Low",
    "17": "Floor Tom High",
    "18": "Mute Triangle",
    "19": "Triangle",
    "20": "Trombone Ensemble",
    "21": "Trombone Ensemble",
    "22": "Trumpet Ensemble",
    "23": "Trumpet Ensemble",
    "24": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_C_01": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Accordion",
    "4": "Accordion",
    "5": "Accordion",
    "6": "Castanet",
    "7": "Clarinet",
    "8": "Clarinet",
    "9": "Clarinet",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "French Horn Ensemble",
    "13": "French Horn Ensemble",
    "14": "Long Guiro",
    "15": "Short Guiro",
    "16": "Closed HiHat",
    "17": "Open HiHat",
    "18": "Kick",
    "19": "Mute Triangle",
    "20": "Triangle"
  },
  "WAVE_MUS_WB_C_02": {
    "0": "Upright Bass",
    "1": "Accordion",
    "2": "Accordion",
    "3": "Accordion",
    "4": "Crash Cymbal",
    "5": "Drawbar Organ",
    "6": "Drawbar Organ",
    "7": "Drawbar Organ",
    "8": "Rhode Piano",
    "9": "Rhode Piano",
    "10": "Closed HiHat",
    "11": "Open HiHat",
    "12": "Analog Kick 1",
    "13": "Analog Kick 2",
    "14": "Acoustic Kick",
    "15": "Ride Cymbal",
    "16": "Analog Snare 1",
    "17": "Analog Snare 2",
    "18": "Acoustic Snare",
    "19": "Splash Cymbal",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "Vibraphone",
    "26": "Vibraphone",
    "27": "Vibraphone"
  },
  "WAVE_MUS_WB_C_03": {
    "0": "Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "Drawbar Organ",
    "4": "Drawbar Organ",
    "5": "Fretless Bass",
    "6": "Fretless Bass",
    "7": "Flute",
    "8": "Flute",
    "9": "Flute",
    "10": "Closed HiHat",
    "11": "Open HiHat",
    "12": "Nylon String Guitar",
    "13": "Nylon String Guitar",
    "14": "Nylon String Guitar",
    "15": "Saxophone",
    "16": "Saxophone",
    "17": "Power Snare",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "Low Floor Tom",
    "22": "High Rack Tom",
    "23": "High Floor Tom",
    "24": "Low Rack Tom"
  },
  "WAVE_MUS_WB_C_04": {
    "0": "Electric Guitar",
    "1": "Electric Guitar",
    "2": "Electric Guitar",
    "3": "Crash Cymbal",
    "4": "Electric Bass",
    "5": "Electric Bass",
    "6": "Electric Bass",
    "7": "Closed HiHat",
    "8": "Open HiHat",
    "9": "Kick",
    "10": "Saxophone",
    "11": "Saxophone",
    "12": "Power Snare",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "Low Floor Tom",
    "17": "High Rack Tom",
    "18": "High Floor Tom",
    "19": "Low Rack Tom",
    "20": "Trombone Ensemble",
    "21": "Trombone Ensemble",
    "22": "Trombone Ensemble",
    "23": "Trumpet Ensemble",
    "24": "Trumpet Ensemble",
    "25": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_C_05": {
    "0": "High Bongo",
    "1": "Shaker",
    "2": "Cowbell",
    "3": "Crash Cymbal",
    "4": "Drawbar Organ",
    "5": "Drawbar Organ",
    "6": "Drawbar Organ",
    "7": "Rhode Piano",
    "8": "Rhode Piano",
    "9": "Glockenspiel",
    "10": "Glockenspiel",
    "11": "Glockenspiel",
    "12": "Open High Conga",
    "13": "Closed HiHat",
    "14": "Analog Kick",
    "15": "Kick",
    "16": "Marimba",
    "17": "Marimba",
    "18": "Marimba",
    "19": "Reverse Cymbal",
    "20": "Analog Snare 1",
    "21": "Analog Snare 2",
    "22": "Synth Bass",
    "23": "Synth Bass",
    "24": "Trombone Ensemble",
    "25": "Trombone Ensemble",
    "26": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_C_06": {
    "0": "Trumpet Ensemble",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Kick",
    "4": "Crash Cymbal",
    "5": "Rhode Piano",
    "6": "Rhode Piano",
    "7": "Closed HiHat",
    "8": "Open HiHat",
    "9": "Jazz Organ",
    "10": "Jazz Organ",
    "11": "Slap Bass",
    "12": "Slap Bass",
    "13": "Slap Bass",
    "14": "Snare",
    "15": "Power Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "Synth Bass",
    "21": "Synth Bass",
    "22": "Timpani",
    "23": "Timpani",
    "24": "Timpani",
    "25": "Low Floor Tom",
    "26": "High Rack Tom",
    "27": "High Floor Tom"
  },
  "WAVE_MUS_WB_C_07": {
    "0": "Accordion",
    "1": "Accordion",
    "2": "High Bongo",
    "3": "Chinese Cymbal",
    "4": "Cowbell",
    "5": "Crash Cymbal",
    "6": "Another Crash",
    "7": "Another Crash 2",
    "8": "Orchestral Cymbal",
    "9": "Electric Bass",
    "10": "Electric Bass",
    "11": "Flute",
    "12": "Flute",
    "13": "Flute",
    "14": "Flute",
    "15": "Clap",
    "16": "Thin Clap",
    "17": "Open High Conga",
    "18": "Open High Conga 2",
    "19": "Closed HiHat",
    "20": "Open HiHat",
    "21": "Kick",
    "22": "Marimba",
    "23": "Marimba",
    "24": "Marimba",
    "25": "Muted Conga",
    "26": "Nylon String Guitar",
    "27": "Nylon String Guitar",
    "28": "Nylon String Guitar",
    "29": "Ride Bell",
    "30": "Ride Cymbal",
    "31": "Side Stick",
    "32": "Shaker",
    "33": "Rimshot Snare",
    "34": "Power Snare",
    "35": "Splash Cymbal",
    "36": "String Ensemble",
    "37": "String Ensemble",
    "38": "String Ensemble",
    "39": "String Ensemble",
    "40": "Tambourine",
    "41": "Solo Violin",
    "42": "Solo Violin",
    "43": "Solo Violin"
  },
  "WAVE_MUS_WB_C_08_B": {
    "0": "Upright Bass",
    "1": "Kick",
    "2": "Kick + Crash",
    "3": "Sync Lead",
    "4": "Clap/Snare thing",
    "5": "Dubstep Snare",
    "6": "Cowbell",
    "7": "Crash Cymbal",
    "8": "Closed Dance HiHat",
    "9": "Open Dance HiHat",
    "10": "Resonant Synth",
    "11": "Resonant Synth",
    "12": "Harpsichord",
    "13": "Harpsichord",
    "14": "Harpsichord",
    "15": "Solo Trumpet",
    "16": "Solo Trumpet",
    "17": "Splash Cymbal",
    "18": "FM Bass",
    "19": "Snare",
    "20": "Vocoder 1 \"I can't stop\"",
    "21": "Vocoder 2 \"You have me and\""
  },
  "WAVE_MUS_WB_C_08_W": {
    "0": "Upright Bass",
    "1": "Kick",
    "2": "Crash Cymbal",
    "3": "Glockenspiel",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Closed HiHat",
    "11": "Open HiHat",
    "12": "Erhu (????)",
    "13": "Oboe",
    "14": "Oboe",
    "15": "Pizzicato String Ensemble",
    "16": "Rim Hit",
    "17": "Rimshot Snare",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "Low Floor Tom",
    "22": "High Rack Tom",
    "23": "High Floor Tom",
    "24": "Low Rack Tom",
    "25": "Vibraphone",
    "26": "Vibraphone"
  },
  "WAVE_MUS_WB_C_10_B": {
    "0": "Choir",
    "1": "Choir",
    "2": "Crash Cymbal",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Closed HiHat",
    "8": "Open HiHat",
    "9": "Kick",
    "10": "Music Box",
    "11": "Music Box",
    "12": "Flute",
    "13": "Flute",
    "14": "Flute",
    "15": "Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "Synth Bass",
    "21": "Synth Bass"
  },
  "WAVE_MUS_WB_C_10_W": {
    "0": "High Bongo",
    "1": "Crash Cymbal",
    "2": "Fretless Bass",
    "3": "Fretless Bass",
    "4": "French Horn",
    "5": "French Horn",
    "6": "Open High Conga",
    "7": "Open High Conga 2",
    "8": "Kick",
    "9": "Marimba",
    "10": "Marimba",
    "11": "Clicky Drum Thing",
    "12": "Oboe",
    "13": "Oboe",
    "14": "Flute",
    "15": "Flute",
    "16": "Flute",
    "17": "Flute",
    "18": "Side Stick",
    "19": "String Ensemble",
    "20": "String Ensemble"
  },
  "WAVE_MUS_WB_R_A": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Crash Cymbal 1",
    "4": "Crash Cymbal 2",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Marimba",
    "10": "Marimba",
    "11": "Flute",
    "12": "Flute",
    "13": "Flute",
    "14": "Flute",
    "15": "Rimshot Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "Tambourine",
    "21": "Vibraphone",
    "22": "Vibraphone",
    "23": "Vibraphone"
  },
  "WAVE_MUS_WB_R_B_SP": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Crash Cymbal 1",
    "4": "Crash Cymbal 2",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "Marimba",
    "10": "Marimba",
    "11": "Marimba",
    "12": "Flute",
    "13": "Flute",
    "14": "Flute",
    "15": "Flute",
    "16": "Pizzicato String Ensemble",
    "17": "Pizzicato String Ensemble",
    "18": "Pizzicato String Ensemble",
    "19": "Pizzicato String Ensemble",
    "20": "Pizzicato String Ensemble",
    "21": "Rimshot Snare",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "Triangle",
    "27": "Whistle"
  },
  "WAVE_MUS_WB_R_B_SU": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Crash Cymbal 1",
    "4": "Crash Cymbal 2",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "Marimba",
    "10": "Marimba",
    "11": "Marimba",
    "12": "Flute",
    "13": "Pizzicato String Ensemble",
    "14": "Pizzicato String Ensemble",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble",
    "17": "Pizzicato String Ensemble",
    "18": "Rimshot Snare",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "Triangle",
    "24": "Whistle"
  },
  "WAVE_MUS_WB_R_B_AU": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Crash Cymbal 1",
    "4": "Crash Cymbal 2",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Marimba",
    "12": "Marimba",
    "13": "Marimba",
    "14": "Flute",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble",
    "17": "Pizzicato String Ensemble",
    "18": "Pizzicato String Ensemble",
    "19": "Pizzicato String Ensemble",
    "20": "Rimshot Snare",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "Triangle",
    "26": "Whistle"
  },
  "WAVE_MUS_WB_R_B_WI": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Crash Cymbal 1",
    "4": "Crash Cymbal 2",
    "5": "Electric Piano",
    "6": "Electric Piano",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "French Horn Ensemble",
    "10": "French Horn Ensemble",
    "11": "Marimba",
    "12": "Marimba",
    "13": "Marimba",
    "14": "Flute",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble",
    "17": "Pizzicato String Ensemble",
    "18": "Pizzicato String Ensemble",
    "19": "Pizzicato String Ensemble",
    "20": "Rimshot Snare",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "Triangle",
    "26": "Whistle"
  },
  "WAVE_MUS_WB_R_C_SP": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Flute",
    "6": "Flute",
    "7": "Flute",
    "8": "Reverse Cymbal",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Timpani",
    "15": "Trombone Ensemble",
    "16": "Trombone Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_R_C_AU": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Flute",
    "6": "Flute",
    "7": "Flute",
    "8": "Reverse Cymbal",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Timpani",
    "15": "Trombone Ensemble",
    "16": "Trombone Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Xylophone",
    "21": "Xylophone"
  },
  "WAVE_MUS_WB_R_C_WI": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Glockenspiel",
    "6": "Glockenspiel",
    "7": "Flute",
    "8": "Flute",
    "9": "Flute",
    "10": "Reverse Cymbal",
    "11": "Orchestral Snare",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "Timpani",
    "16": "Timpani",
    "17": "Trombone Ensemble",
    "18": "Trombone Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble",
    "21": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_R_D_SP": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Flute",
    "9": "Flute",
    "10": "Flute",
    "11": "Flute",
    "12": "Orchestral Snare",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble",
    "21": "Tuba",
    "22": "Tuba"
  },
  "WAVE_MUS_WB_R_D_SU": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Harp",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Timpani",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Tuba",
    "19": "Tuba"
  },
  "WAVE_MUS_WB_R_D_AU": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Orchestral Cymbal",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "Harp",
    "9": "Harp",
    "10": "Harp",
    "11": "Harp",
    "12": "Orchestral Snare",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble",
    "21": "Tuba",
    "22": "Tuba"
  },
  "WAVE_MUS_WB_R_D_WI": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Harp",
    "9": "Music Box",
    "10": "Orchestral Snare",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "Timpani",
    "16": "Trumpet Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Tuba",
    "20": "Tuba"
  },
  "WAVE_MUS_WB_R_E_SP": {
    "0": "Crash Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Harp",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Tubular Bells",
    "15": "Tubular Bells"
  },
  "WAVE_MUS_WB_R_E_SU": {
    "0": "Crash Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Saxophone",
    "6": "Saxophone",
    "7": "Saxophone",
    "8": "Orchestral Snare",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Tubular Bells",
    "14": "Tubular Bells"
  },
  "WAVE_MUS_WB_R_E_AU": {
    "0": "Crash Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harpsichord",
    "6": "Harpsichord",
    "7": "Harpsichord",
    "8": "Harpsichord",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Tubular Bells",
    "15": "Tubular Bells"
  },
  "WAVE_MUS_WB_R_E_WI": {
    "0": "Crash Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Orchestral Snare",
    "6": "String Ensemble",
    "7": "String Ensemble",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "Tubular Bells",
    "11": "Tubular Bells",
    "12": "Vibraphone",
    "13": "Vibraphone",
    "14": "Vibraphone"
  },
  "WAVE_MUS_WB_R_F": {
    "0": "Accordion",
    "1": "Accordion",
    "2": "Accordion",
    "3": "Crash Cymbal",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Thin Clap",
    "7": "Kick",
    "8": "Nylon String Guitar",
    "9": "Nylon String Guitar",
    "10": "Nylon String Guitar",
    "11": "Flute",
    "12": "Flute",
    "13": "Flute",
    "14": "Flute",
    "15": "Reverse Cymbal",
    "16": "Rim Hit",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble"
  },
  "WAVE_MUS_WB_H_01": {
    "0": "Kick",
    "1": "Shaker",
    "2": "Traffic sfx",
    "3": "Chinese Cymbal",
    "4": "Clarinet",
    "5": "Clarinet",
    "6": "Clarinet",
    "7": "Crash Cymbal",
    "8": "Fretless Bass",
    "9": "Fretless Bass",
    "10": "Flute",
    "11": "Flute",
    "12": "Flute",
    "13": "Flute",
    "14": "French Horn Ensemble",
    "15": "Acoustic Piano",
    "16": "Acoustic Piano",
    "17": "Acoustic Piano",
    "18": "Closed HiHat",
    "19": "Open HiHat",
    "20": "Nylon String Guitar",
    "21": "Nylon String Guitar",
    "22": "Nylon String Guitar",
    "23": "Orchestral Snare",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "Low Floor Tom",
    "27": "High Rack Tom",
    "28": "Wind sfx"
  },
  "WAVE_MUS_WB_H_02": {
    "0": "Rhode Piano",
    "1": "Rhode Piano",
    "2": "Glockenspiel",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Helicopter sfx",
    "10": "Airplane sfx",
    "11": "Rhyhorn cry",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "Tubular Bells",
    "17": "Tubular Bells"
  },
  "WAVE_MUS_WB_H_03": {
    "0": "Chinese Cymbal",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Clarinet",
    "4": "Crash Cymbal",
    "5": "Drawbar Organ",
    "6": "Drawbar Organ",
    "7": "Drawbar Organ",
    "8": "Closed HiHat",
    "9": "Kick",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Power Snare",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Low Floor Tom",
    "20": "High Rack Tom",
    "21": "Low Rack Tom",
    "22": "Train sfx"
  },
  "WAVE_MUS_WB_H_04": {
    "0": "Harpsichord",
    "1": "Harpsichord",
    "2": "Harpsichord",
    "3": "Vocal \"nooo-woooh\"",
    "4": "Nylon String Guitar",
    "5": "Nylon String Guitar",
    "6": "Shaker",
    "7": "Distorted Square",
    "8": "Distorted Square",
    "9": "Distorted Square",
    "10": "Vocal \"eh\"",
    "11": "Vocal \"heh\"",
    "12": "Vocal \"huh\"",
    "13": "Vocal \"hah\"",
    "14": "Vocal \"haaah\"",
    "15": "Vocal \"hee\"",
    "16": "Vocal \"he-\"",
    "17": "Vocal \"ee\" 1",
    "18": "Vocal \"ee\" 2",
    "19": "Vocal \"heeeh\"",
    "20": "Vocal \"ki\"",
    "21": "Vocal \"wo\"",
    "22": "Vocal \"oh\" 1",
    "23": "Vocal \"oh\" 2",
    "24": "Vocal \"who\"",
    "25": "Vocal \"zee\"",
    "26": "Vocal \"dee\"",
    "27": "Vocal \"eyyy\"",
    "28": "Vocal \"hoeh\"",
    "29": "Vocal \"u-\"",
    "30": "Vocah \"breh\"",
    "31": "Vocal \"so\"",
    "32": "Vocal \"ta\"",
    "33": "Vocal \"ee-eh\" 1",
    "34": "Vocal \"ee-eh\" 2",
    "35": "Beatbox Kick",
    "36": "Beatbox Kick 2",
    "37": "Beatbox Snare 1",
    "38": "Beatbox Click",
    "39": "Beatbox Hat 1",
    "40": "Beatbox Fill",
    "41": "Beatbox Snare 2",
    "42": "Beatbox Hat 2"
  },
  "WAVE_MUS_WB_H_05": {
    "0": "Shaker",
    "1": "Solo Cello",
    "2": "Solo Cello",
    "3": "Solo Cello",
    "4": "Choir Ahhs",
    "5": "Choir Ahhs",
    "6": "Choir Ahhs",
    "7": "Choir Ahhs",
    "8": "Crash Cymbal",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Open High Conga",
    "15": "Kick",
    "16": "Power Snare",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "High Floor Tom",
    "22": "Mute Triangle",
    "23": "Triangle",
    "24": "Chimes"
  },
  "WAVE_MUS_WB_POKECEN": {
    "0": "Kick 1",
    "1": "Kick 2",
    "2": "Kick 3",
    "3": "High Bongo",
    "4": "Shaker",
    "5": "Chinese Cymbal",
    "6": "Clarinet Ensemble",
    "7": "Clarinet Ensemble",
    "8": "Clarinet Ensemble",
    "9": "Cowbell",
    "10": "Crash Cymbal",
    "11": "Orchestral Cymbal",
    "12": "Fretless Bass",
    "13": "Fretless Bass",
    "14": "Rhode Piano",
    "15": "Rhode Piano",
    "16": "Flute",
    "17": "Flute",
    "18": "Flute",
    "19": "Flute",
    "20": "Clap 1",
    "21": "Clap 2",
    "22": "High Conga",
    "23": "Closed HiHat",
    "24": "Open HiHat",
    "25": "Marimba",
    "26": "Marimba",
    "27": "Marimba",
    "28": "Muted High Conga",
    "29": "Nylon String Guitar",
    "30": "Nylon String Guitar",
    "31": "Nylon String Guitar",
    "32": "Nylon String Guitar",
    "33": "Reverse Cymbal",
    "34": "Ride Bell",
    "35": "Ride Cymbal",
    "36": "Side Stick",
    "37": "Shaker",
    "38": "Snare",
    "39": "Analog Snare",
    "40": "Orchestral Snare",
    "41": "Power Snare",
    "42": "Splash Cymbal",
    "43": "String Ensemble",
    "44": "String Ensemble",
    "45": "String Ensemble",
    "46": "String Ensemble",
    "47": "String Ensemble",
    "48": "Tambourine",
    "49": "Low Floor Tom",
    "50": "High Rack Tom",
    "51": "High Floor Tom",
    "52": "Low Rack Tom",
    "53": "Triangle",
    "54": "Marimba",
    "55": "Marimba"
  },
  "WAVE_MUS_WB_GYM": {
    "0": "Dance Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Marschall Guitar",
    "7": "Marschall Guitar",
    "8": "Marschall Guitar",
    "9": "French Horn Ensemble",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "Closed Acoustic HiHat",
    "13": "Open Acoustic HiHat",
    "14": "Ride Cymbal",
    "15": "Power Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "Low Floor Tom",
    "21": "High Rack Tom",
    "22": "High Floor Tom",
    "23": "Low Rack Tom",
    "24": "Trumpet Ensemble",
    "25": "Trumpet Ensemble",
    "26": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_GYM_C05": {
    "0": "Dance Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Marschall Guitar",
    "7": "Marschall Guitar",
    "8": "Marschall Guitar",
    "9": "French Horn Ensemble",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "Closed Acoustic HiHat",
    "13": "Open Acoustic HiHat",
    "14": "Ride Cymbal",
    "15": "Turbine SFX",
    "16": "Power Snare",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "Low Floor Tom",
    "22": "High Rack Tom",
    "23": "High Floor Tom",
    "24": "Low Rack Tom",
    "25": "Trumpet Ensemble",
    "26": "Trumpet Ensemble",
    "27": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_LABO": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Clarinet",
    "4": "Clarinet",
    "5": "Clarinet",
    "6": "Flute",
    "7": "Flute",
    "8": "Flute",
    "9": "Glockenspiel",
    "10": "Glockenspiel",
    "11": "Glockenspiel",
    "12": "Nylon String Guitar",
    "13": "Nylon String Guitar",
    "14": "Nylon String Guitar",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble"
  },
  "WAVE_MUS_WB_GATE": {
    "0": "Kick",
    "1": "Fretless Bass",
    "2": "Fretless Bass",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Rhode Piano",
    "6": "Rhode Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Closed Acoustic HiHat",
    "13": "Open Acoustic HiHat",
    "14": "Side Stick",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble"
  },
  "WAVE_MUS_WB_GEAR_STATION": {
    "0": "Chinese Cymbal",
    "1": "Crash Cymbal",
    "2": "Fretless Bass",
    "3": "Fretless Bass",
    "4": "Electric Guitar",
    "5": "Electric Guitar",
    "6": "Electric Guitar",
    "7": "Electric Guitar",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Closed HiHat",
    "15": "Open HiHat",
    "16": "Kick",
    "17": "Drawbar Organ",
    "18": "Drawbar Organ",
    "19": "Power Guitar",
    "20": "Power Guitar",
    "21": "Guitar Squeal",
    "22": "Hard Snare",
    "23": "Tom 1",
    "24": "Tom 2",
    "25": "Tom 3",
    "26": "Tom 4"
  },
  "WAVE_MUS_WB_BATTLE_SUBWAY": {
    "0": "Low Percussive",
    "1": "Tabla",
    "2": "Tabla",
    "3": "Tabla",
    "4": "Tabla",
    "5": "Jazz Bass",
    "6": "Jazz Bass",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Kick",
    "10": "Sync Lead",
    "11": "Clap/Snare thing",
    "12": "Dubstep Snare",
    "13": "Crash Cymbal",
    "14": "Closed HiHat",
    "15": "Open HiHat",
    "16": "Solo Trumpet",
    "17": "Slap Bass",
    "18": "Slap Bass",
    "19": "Slap Bass",
    "20": "Synth Bass",
    "21": "Synth Bass",
    "22": "Train SFX 1",
    "23": "Train SFX 2",
    "24": "Tubular Bells"
  },
  "WAVE_MUS_WB_PLEASURE_BOAT": {
    "0": "French Horn",
    "1": "French Horn",
    "2": "French Horn",
    "3": "French Horn",
    "4": "Harp",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble"
  },
  "WAVE_MUS_WB_PALACE": {
    "0": "Orchestral Cymbal",
    "1": "French Horn",
    "2": "French Horn",
    "3": "French Horn",
    "4": "French Horn",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Oboe",
    "9": "Oboe",
    "10": "Oboe",
    "11": "Pizzicato String Ensemble",
    "12": "Orchestral Snare",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Trombone Ensemble",
    "19": "Trombone Ensemble",
    "20": "Trombone Ensemble",
    "21": "Tubular Bells"
  },
  "WAVE_MUS_WB_PALACE2": {
    "0": "Clean Guitar",
    "1": "Clean Guitar",
    "2": "Clean Guitar",
    "3": "Clean Guitar",
    "4": "Crash Cymbal",
    "5": "Drawbar Organ",
    "6": "Drawbar Organ",
    "7": "Drawbar Organ",
    "8": "Fretless Bass",
    "9": "Fretless Bass",
    "10": "Fretless Bass",
    "11": "Fretless Bass",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Acoustic Piano",
    "15": "Acoustic Piano",
    "16": "Acoustic Piano",
    "17": "Acoustic Piano",
    "18": "Kick sfx",
    "19": "Tom",
    "20": "Tom",
    "21": "Tom",
    "22": "Open High Conga",
    "23": "Open High Conga 2",
    "24": "Muted Conga"
  },
  "WAVE_MUS_WB_UNITED_NATIONS": {
    "0": "Crash Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Harp",
    "9": "Flute",
    "10": "Flute",
    "11": "Flute",
    "12": "Rimshot Snare",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Timpani",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble",
    "21": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_POKEMON_LEAGUE": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "Orchestral Cymbal",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "Harp",
    "7": "Harp",
    "8": "Orchestral Snare",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Tuba",
    "15": "Tuba"
  },
  "WAVE_MUS_WB_N_CASTLE_BRIDGE": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "Solo Cello",
    "3": "Crash Cymbal",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "Harp",
    "9": "Harp",
    "10": "Harp",
    "11": "Harp",
    "12": "Closed Electric HiHat",
    "13": "Open Electric HiHat",
    "14": "Electric Kick",
    "15": "Electric Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Trombone Ensemble",
    "20": "Trombone Ensemble",
    "21": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_N_CASTLE": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "Solo Cello",
    "3": "Choir",
    "4": "Choir",
    "5": "Choir",
    "6": "Pipe Organ",
    "7": "Pipe Organ",
    "8": "Pipe Organ",
    "9": "Pipe Organ",
    "10": "Orchestral Cymbal",
    "11": "Orchestral Snare",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Tubular Bells",
    "19": "Vibraphone",
    "20": "Vibraphone",
    "21": "Vibraphone"
  },
  "WAVE_MUS_WB_D_01": {
    "0": "Upright Bass",
    "1": "Splash Cymbal",
    "2": "Crash Cymbal",
    "3": "Rhode Piano",
    "4": "Rhode Piano",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "Closed HiHat",
    "10": "Open HiHat",
    "11": "Kick",
    "12": "Pizzicato String Ensemble",
    "13": "Pizzicato String Ensemble",
    "14": "Pizzicato String Ensemble",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble",
    "17": "Snare Clap Thing",
    "18": "Side Stick",
    "19": "Snare 1",
    "20": "Snare 2",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble"
  },
  "WAVE_MUS_WB_D_02": {
    "0": "Solo Cello",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Clarinet",
    "4": "Suspended Cymbal",
    "5": "Rhode Piano",
    "6": "Rhode Piano",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "French Horn Ensemble",
    "10": "French Horn Ensemble",
    "11": "Pizzicato String Ensemble",
    "12": "Pizzicato String Ensemble",
    "13": "Pizzicato String Ensemble",
    "14": "Shaker",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Timpani",
    "20": "Vibraphone",
    "21": "Vibraphone"
  },
  "WAVE_MUS_WB_D_03": {
    "0": "Kick 1",
    "1": "Kick 2",
    "2": "Chinese Cymbal",
    "3": "Marschall Guitar",
    "4": "Marschall Guitar",
    "5": "Marschall Guitar",
    "6": "Marschall Guitar",
    "7": "Rhode Piano",
    "8": "Rhode Piano",
    "9": "Clap",
    "10": "Mute Triangle",
    "11": "Triangle",
    "12": "Tubular Bells",
    "13": "Tubular Bells"
  },
  "WAVE_MUS_WB_D_04": {
    "0": "Kick",
    "1": "Crash Cymbal",
    "2": "Fretless Bass",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Rhode Piano",
    "6": "Rhode Piano",
    "7": "Closed HiHat",
    "8": "Open HiHat",
    "9": "Marimba",
    "10": "Marimba",
    "11": "Oboe",
    "12": "Oboe",
    "13": "Oboe",
    "14": "Oboe",
    "15": "Clap",
    "16": "Folk Guitar",
    "17": "Folk Guitar",
    "18": "Folk Guitar",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "Vibraphone",
    "24": "Vibraphone",
    "25": "Vibraphone"
  },
  "WAVE_MUS_WB_D_05": {
    "0": "Rhode Piano",
    "1": "Rhode Piano",
    "2": "Acoustic Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Closed HiHat",
    "7": "Kick",
    "8": "Oboe",
    "9": "Oboe",
    "10": "Pizzicato String Ensemble",
    "11": "Pizzicato String Ensemble",
    "12": "Pizzicato String Ensemble",
    "13": "Pizzicato String Ensemble",
    "14": "Pizzicato String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Synth Bass",
    "20": "Synth Bass"
  },
  "WAVE_MUS_WB_D_06": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Low Strings",
    "4": "Crash Cymbal",
    "5": "Suspended Cymbal",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "French Horn Ensemble",
    "10": "Harp",
    "11": "Harp",
    "12": "Harp",
    "13": "Koto",
    "14": "Koto",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble",
    "17": "Pizzicato String Ensemble",
    "18": "Pizzicato String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "Shakuhachi",
    "22": "Mute Triangle",
    "23": "Triangle"
  },
  "WAVE_MUS_WB_D_07": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "Solo Cello",
    "3": "Wind sfx",
    "4": "String Ensemble",
    "5": "String Ensemble",
    "6": "String Ensemble",
    "7": "String Ensemble",
    "8": "Timpani"
  },
  "WAVE_MUS_WB_D_CHAMPROAD": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "Wind sfx",
    "7": "Pizzicato String Ensemble",
    "8": "Pizzicato String Ensemble",
    "9": "Pizzicato String Ensemble",
    "10": "Pizzicato String Ensemble",
    "11": "Rimshot Snare",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "Timpani",
    "17": "Timpani",
    "18": "Tuba",
    "19": "Tuba",
    "20": "Tubular Bells",
    "21": "Tubular Bells"
  },
  "WAVE_MUS_WB_E_TSURETEKE1": {
    "0": "Upright Bass",
    "1": "Rhode Piano",
    "2": "Rhode Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Open High Conga",
    "7": "Marimba",
    "8": "Marimba",
    "9": "Marimba",
    "10": "Muted High Conga",
    "11": "Pizzicato String Ensemble",
    "12": "Pizzicato String Ensemble",
    "13": "Pizzicato String Ensemble"
  },
  "WAVE_MUS_WB_E_TSURETEKE2": {
    "0": "Upright Bass",
    "1": "Rhode Piano",
    "2": "Rhode Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Harp",
    "7": "Harp",
    "8": "Harp",
    "9": "Open High Conga",
    "10": "Marimba",
    "11": "Marimba",
    "12": "Marimba",
    "13": "Muted High Conga",
    "14": "Pizzicato String Ensemble",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble"
  },
  "WAVE_MUS_WB_E_RIVAL": {
    "0": "Trumpet Ensemble",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Kick",
    "6": "Chinese Cymbal",
    "7": "Crash Cymbal",
    "8": "Electric Guitar",
    "9": "Electric Guitar",
    "10": "Electric Guitar",
    "11": "Marschall Guitar",
    "12": "Marschall Guitar",
    "13": "Clap",
    "14": "Closed HiHat",
    "15": "Open HiHat",
    "16": "Slap Bass",
    "17": "Slap Bass",
    "18": "Slap Bass",
    "19": "Snare",
    "20": "Orchestral Snare",
    "21": "Power Snare"
  },
  "WAVE_MUS_WB_E_SUPPORT": {
    "0": "Kick",
    "1": "Clean Guitar",
    "2": "Clean Guitar",
    "3": "Clean Guitar",
    "4": "Clean Guitar",
    "5": "Rhode Piano",
    "6": "Rhode Piano",
    "7": "Power Snare",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "Tambourine",
    "12": "Vibraphone",
    "13": "Vibraphone",
    "14": "Vibraphone"
  },
  "WAVE_MUS_WB_E_DOCTOR": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Kick",
    "3": "Drawbar Organ",
    "4": "Drawbar Organ",
    "5": "Drawbar Organ",
    "6": "Rhode Piano",
    "7": "Rhode Piano",
    "8": "Closed HiHat",
    "9": "Open HiHat",
    "10": "Orchestral Snare",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Trumpet Ensemble",
    "14": "Trumpet Ensemble",
    "15": "Trumpet Ensemble",
    "16": "Solo Violin",
    "17": "Solo Violin",
    "18": "Solo Violin"
  },
  "WAVE_MUS_WB_E_DOCTOR2": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "High Bongo",
    "4": "Shaker",
    "5": "Clarinet",
    "6": "Clarinet",
    "7": "Clarinet",
    "8": "Nylon String Guitar",
    "9": "Nylon String Guitar",
    "10": "Nylon String Guitar",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble"
  },
  "WAVE_MUS_WB_E_PLASMA": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync Lead",
    "3": "Crash Cymbal",
    "4": "Closed Dance HiHat",
    "5": "Open Dance HiHat",
    "6": "Electric Guitar",
    "7": "Electric Guitar",
    "8": "Electric Guitar",
    "9": "Electric Guitar",
    "10": "Electric Guitar",
    "11": "Orchestra Hit 1",
    "12": "Orchestra Hit 2",
    "13": "Solo Trumpet",
    "14": "Slap Bass",
    "15": "Power Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "FM Bass",
    "19": "Timpani"
  },
  "WAVE_MUS_WB_E_N": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Clarinet",
    "3": "Clarinet",
    "4": "Music Box",
    "5": "Music Box",
    "6": "Pizzicato String Ensemble",
    "7": "Pizzicato String Ensemble",
    "8": "Pizzicato String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "Timpani",
    "12": "Timpani",
    "13": "Timpani"
  },
  "WAVE_MUS_WB_E_SAGE": {
    "0": "Choir Ahhs",
    "1": "Choir Ahhs",
    "2": "Choir Ahhs",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Pizzicato String Ensemble",
    "8": "Pizzicato String Ensemble",
    "9": "Pizzicato String Ensemble",
    "10": "Pizzicato String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani"
  },
  "WAVE_MUS_WB_E_G_CIS": {
    "0": "Solo Cello",
    "1": "Orchestral Cymbal",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "Flute",
    "5": "Flute",
    "6": "Flute",
    "7": "String Ensemble",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "Timpani"
  },
  "WAVE_MUS_WB_E_INISHIE": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Acoustic Guitar",
    "3": "Acoustic Guitar",
    "4": "Acoustic Guitar",
    "5": "Acoustic Guitar",
    "6": "Acoustic Guitar",
    "7": "Acoustic Guitar",
    "8": "Thin Clap",
    "9": "Flute",
    "10": "Flute",
    "11": "Flute",
    "12": "String Ensemble",
    "13": "String Ensemble"
  },
  "WAVE_MUS_WB_E_EMOTION": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Cymbal",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Pizzicato String Ensemble",
    "10": "Pizzicato String Ensemble",
    "11": "Cymbal",
    "12": "String Ensemble",
    "13": "String Ensemble"
  },
  "WAVE_MUS_WB_E_TROUBLE": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "Orchestral Snare",
    "4": "String Ensemble",
    "5": "String Ensemble",
    "6": "String Ensemble",
    "7": "String Ensemble",
    "8": "Timpani",
    "9": "Timpani",
    "10": "Trombone Ensemble",
    "11": "Trombone Ensemble",
    "12": "Xylophone",
    "13": "Xylophone",
    "14": "Xylophone"
  },
  "WAVE_MUS_WB_E_LAST": {
    "0": "Suspended Cymbal",
    "1": "Orchestral Cymbal",
    "2": "Acoustic Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Timpani"
  },
  "WAVE_MUS_WB_E_HANDSOME": {
    "0": "Crash Cymbal",
    "1": "Fretless Bass",
    "2": "Fretless Bass",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "Kick",
    "9": "Rimshot Snare",
    "10": "Power Snare",
    "11": "Low Floor Tom",
    "12": "High Rack Tom",
    "13": "High Floor Tom",
    "14": "Low Rack Tom",
    "15": "Trombone Ensemble",
    "16": "Trombone Ensemble",
    "17": "Trombone Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_E_CHAMPION": {
    "0": "Kick",
    "1": "Fretless Bass",
    "2": "Fretless Bass",
    "3": "Fretless Bass",
    "4": "Flute",
    "5": "Flute",
    "6": "Flute",
    "7": "Flute",
    "8": "Open High Conga",
    "9": "Muted Conga",
    "10": "Nylon String Guitar",
    "11": "Nylon String Guitar",
    "12": "Nylon String Guitar",
    "13": "Side Stick",
    "14": "Shaker",
    "15": "Splash Cymbal",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble"
  },
  "WAVE_MUS_WB_E_KANRANSYA": {
    "0": "Bright Piano",
    "1": "Bright Piano",
    "2": "Kick",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Fretless Bass",
    "7": "Closed HiHat",
    "8": "Percussive Organ",
    "9": "Percussive Organ",
    "10": "Percussive Organ",
    "11": "Clap",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "Triangle"
  },
  "WAVE_MUS_WB_E_N_CASTLE": {
    "0": "Solo Cello",
    "1": "Orchestral Cymbal",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "Zap sfx",
    "7": "Wind sfx",
    "8": "Orchestral Snare",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Trumpet Ensemble",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Low Wind"
  },
  "WAVE_MUS_WB_E_LEGEND_BORN_B": {
    "0": "Growl",
    "1": "Reshiram SFX",
    "2": "Solo Cello",
    "3": "Choir",
    "4": "Choir",
    "5": "Choir",
    "6": "Choir",
    "7": "Choir",
    "8": "Suspended Cymbal",
    "9": "Orchestral Cymbal",
    "10": "Harp",
    "11": "Harp",
    "12": "Harp",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Low Wind"
  },
  "WAVE_MUS_WB_E_LEGEND_BORN_W": {
    "0": "Growl",
    "1": "Zekrom SFX",
    "2": "Solo Cello",
    "3": "Choir",
    "4": "Choir",
    "5": "Choir",
    "6": "Choir",
    "7": "Choir",
    "8": "Suspended Cymbal",
    "9": "Orchestral Cymbal",
    "10": "Harp",
    "11": "Harp",
    "12": "Harp",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Low Wind"
  },
  "WAVE_MUS_WB_MSL_FIELD": {
    "0": "Solo Cello",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "French Horn",
    "4": "French Horn",
    "5": "French Horn",
    "6": "French Horn",
    "7": "Glockenspiel",
    "8": "Glockenspiel",
    "9": "Glockenspiel",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble"
  },
  "WAVE_MUS_WB_MSL_DRESSUP": {
    "0": "Fretless Bass",
    "1": "Fretless Bass",
    "2": "Closed HiHat",
    "3": "Open HiHat",
    "4": "Kick",
    "5": "Marimba",
    "6": "Marimba",
    "7": "Marimba",
    "8": "Percussive Organ",
    "9": "Percussive Organ",
    "10": "Percussive Organ",
    "11": "Rim Hit",
    "12": "Vibraphone",
    "13": "Vibraphone",
    "14": "Vibraphone"
  },
  "WAVE_MUS_WB_MSL_BEFORE": {
    "0": "Crash Cymbal",
    "1": "Orchestral Cymbal",
    "2": "Flute",
    "3": "Flute",
    "4": "Flute",
    "5": "Flute",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "French Horn Ensemble",
    "10": "Harp",
    "11": "Harp",
    "12": "Harp",
    "13": "Rimshot Snare",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "Timpani",
    "19": "Timpani",
    "20": "Timpani"
  },
  "WAVE_MUS_WB_MSL_01": {
    "0": "Acoustic Piano",
    "1": "Acoustic Piano",
    "2": "Drum Loop",
    "3": "Sync Lead",
    "4": "Rhode Piano",
    "5": "Rhode Piano",
    "6": "Resonant Synth",
    "7": "Resonant Synth",
    "8": "Clap/Snare thing",
    "9": "Dubstep Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Synth Bass",
    "15": "Synth Bass",
    "16": "Trumpet Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Vibraphone",
    "20": "Vibraphone",
    "21": "Vibraphone"
  },
  "WAVE_MUS_WB_MSL_02": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Castanet",
    "4": "Clarinet",
    "5": "Clarinet",
    "6": "Clarinet",
    "7": "Crash Cymbal",
    "8": "Flute",
    "9": "Flute",
    "10": "Flute",
    "11": "Flute",
    "12": "Harp",
    "13": "Harp",
    "14": "Harp",
    "15": "Closed HiHat",
    "16": "Open HiHat",
    "17": "Pizzicato String Ensemble",
    "18": "Pizzicato String Ensemble",
    "19": "Pizzicato String Ensemble",
    "20": "Pizzicato String Ensemble",
    "21": "Pizzicato String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "Mute Triangle",
    "27": "Triangle",
    "28": "Vibraphone",
    "29": "Vibraphone",
    "30": "Vibraphone"
  },
  "WAVE_MUS_WB_MSL_03": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Acoustic Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Clap",
    "11": "Open HiHat",
    "12": "Kick",
    "13": "Saxophone",
    "14": "Saxophone",
    "15": "Saxophone",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "High Rack Tom",
    "21": "High Floor Tom",
    "22": "Low Rack Tom",
    "23": "Mute Triangle",
    "24": "Triangle",
    "25": "Vibraphone",
    "26": "Vibraphone",
    "27": "Chimes"
  },
  "WAVE_MUS_WB_MSL_04": {
    "0": "Accordion",
    "1": "Accordion",
    "2": "Accordion",
    "3": "Kick",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Splash Cymbal",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble"
  },
  "WAVE_MUS_WB_EYE_01": {
    "0": "Kick",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Crash Cymbal",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Clap",
    "7": "Marimba",
    "8": "Marimba",
    "9": "Marimba",
    "10": "Nylon String Guitar",
    "11": "Nylon String Guitar",
    "12": "Nylon String Guitar",
    "13": "Low Floor Tom",
    "14": "High Floor Tom",
    "15": "Low Rack Tom"
  },
  "WAVE_MUS_WB_EYE_02": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Shaker 1",
    "4": "Rhode Piano",
    "5": "Rhode Piano",
    "6": "Nylon String Guitar",
    "7": "Nylon String Guitar",
    "8": "Nylon String Guitar",
    "9": "Shaker 2",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Vibraphone",
    "14": "Vibraphone",
    "15": "Vibraphone"
  },
  "WAVE_MUS_WB_EYE_03": {
    "0": "Castanet",
    "1": "Rhode Piano",
    "2": "Rhode Piano",
    "3": "Kick",
    "4": "Music Box",
    "5": "Music Box",
    "6": "Music Box",
    "7": "Percussive Organ",
    "8": "Percussive Organ",
    "9": "Percussive Organ",
    "10": "Orchestral Snare",
    "11": "Tambourine"
  },
  "WAVE_MUS_WB_EYE_04": {
    "0": "Kick",
    "1": "Crash Cymbal",
    "2": "Marschall Guitar",
    "3": "Marschall Guitar",
    "4": "Marschall Guitar",
    "5": "Open HiHat",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Slap Bass",
    "9": "Slap Bass",
    "10": "Rimshot Snare",
    "11": "Power Snare",
    "12": "Tambourine",
    "13": "Low Floor Tom",
    "14": "High Rack Tom",
    "15": "Low Rack Tom"
  },
  "WAVE_MUS_WB_EYE_05": {
    "0": "Acoustic Piano",
    "1": "Acoustic Piano",
    "2": "Kick",
    "3": "Crash Cymbal",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Saxophone",
    "10": "Saxophone",
    "11": "Saxophone",
    "12": "Orchestral Snare",
    "13": "Rimshot Snare",
    "14": "Synth Bass",
    "15": "Synth Bass"
  },
  "WAVE_MUS_WB_EYE_06": {
    "0": "Upright Bass",
    "1": "Kick",
    "2": "Crash Cymbal",
    "3": "Drawbar Organ",
    "4": "Drawbar Organ",
    "5": "Drawbar Organ",
    "6": "Closed HiHat",
    "7": "Open HiHat",
    "8": "Acoustic Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Orchestral Snare",
    "14": "Folk Guitar",
    "15": "Folk Guitar",
    "16": "Folk Guitar",
    "17": "Folk Guitar",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "Tambourine",
    "23": "Vibraphone",
    "24": "Vibraphone"
  },
  "WAVE_MUS_WB_EYE_07": {
    "0": "Kick",
    "1": "Chinese Cymbal",
    "2": "Clean Guitar",
    "3": "Clean Guitar",
    "4": "Clean Guitar",
    "5": "Clean Guitar",
    "6": "Cowbell",
    "7": "Crash Cymbal",
    "8": "Electric Guitar",
    "9": "Electric Guitar",
    "10": "Electric Guitar",
    "11": "Electric Guitar",
    "12": "Electric Piano",
    "13": "Electric Piano",
    "14": "Clap",
    "15": "Closed HiHat",
    "16": "Open HiHat",
    "17": "Reverse Cymbal",
    "18": "Ride Bell",
    "19": "Ride Cymbal",
    "20": "Slap Bass",
    "21": "Snare",
    "22": "Orchestral Snare",
    "23": "Power Snare",
    "24": "Splash Cymbal",
    "25": "String Ensemble",
    "26": "String Ensemble",
    "27": "String Ensemble",
    "28": "String Ensemble",
    "29": "Low Floor Tom",
    "30": "High Rack Tom",
    "31": "High Floor Tom",
    "32": "Low Rack Tom",
    "33": "Trumpet Ensemble",
    "34": "Trumpet Ensemble",
    "35": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_EYE_08": {
    "0": "Upright Bass",
    "1": "Compressed Kick",
    "2": "Kick",
    "3": "Orchestral Cymbal",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Open HiHat",
    "7": "Reverse Cymbal",
    "8": "Snare",
    "9": "Power Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Synth Bass",
    "15": "Synth Bass"
  },
  "WAVE_MUS_WB_EYE_09": {
    "0": "Choir",
    "1": "Choir",
    "2": "Acoustic Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Acoustic Piano",
    "9": "Pizzicato String Ensemble",
    "10": "Pizzicato String Ensemble",
    "11": "Pizzicato String Ensemble",
    "12": "Pizzicato String Ensemble",
    "13": "Vibraphone"
  },
  "WAVE_MUS_WB_EYE_10": {
    "0": "Crash Cymbal",
    "1": "Drawbar Organ",
    "2": "Drawbar Organ",
    "3": "Closed HiHat",
    "4": "Open HiHat",
    "5": "Kick",
    "6": "Clap",
    "7": "Synth Bass",
    "8": "Synth Bass",
    "9": "Trombone Ensemble",
    "10": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_EYE_11": {
    "0": "Orchestral Cymbal",
    "1": "Flute",
    "2": "Flute",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Orchestral Snare",
    "6": "Timpani",
    "7": "Trombone Ensemble",
    "8": "Trombone Ensemble",
    "9": "Trumpet Ensemble",
    "10": "Trumpet Ensemble",
    "11": "Tuba",
    "12": "Tuba"
  },
  "WAVE_MUS_WB_EYE_12": {
    "0": "Kick 1",
    "1": "Kick 2",
    "2": "Crash Cymbal",
    "3": "Drawbar Organ",
    "4": "Drawbar Organ",
    "5": "Fretless Bass",
    "6": "Fretless Bass",
    "7": "Marschall Guitar",
    "8": "Marschall Guitar",
    "9": "Marschall Guitar",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Closed HiHat",
    "13": "Open HiHat",
    "14": "Power Snare",
    "15": "Low Floor Tom",
    "16": "High Rack Tom",
    "17": "High Floor Tom",
    "18": "Low Rack Tom"
  },
  "WAVE_MUS_WB_EYE_13": {
    "0": "Oboe",
    "1": "Oboe",
    "2": "Oboe",
    "3": "Flute",
    "4": "Flute",
    "5": "Flute",
    "6": "Flute",
    "7": "String Ensemble",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble"
  },
  "WAVE_MUS_WB_EYE_PLASMA": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync Lead",
    "3": "Crash Cymbal",
    "4": "Closed Dance HiHat",
    "5": "Open Dance HiHat",
    "6": "Electric Guitar",
    "7": "Marschall Guitar",
    "8": "Electric Guitar",
    "9": "Electric Guitar",
    "10": "Electric Guitar",
    "11": "Resonant Synth",
    "12": "Closed HiHat",
    "13": "Solo Trumpet",
    "14": "Slap Bass",
    "15": "Power Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "Snare",
    "19": "Timpani"
  },
  "WAVE_MUS_WB_VS_NORAPOKE": {
    "0": "Upright Bass",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Trumpet Ensemble",
    "4": "Solo Cello",
    "5": "Crash Cymbal",
    "6": "Flute",
    "7": "Flute",
    "8": "Glockenspiel",
    "9": "Closed HiHat",
    "10": "Open HiHat",
    "11": "Marimba",
    "12": "Solo Trumpet",
    "13": "Solo Trumpet",
    "14": "Pizzicato String Ensemble",
    "15": "Pizzicato String Ensemble",
    "16": "Pizzicato String Ensemble",
    "17": "Kick",
    "18": "Power Snare",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "FM Bass",
    "24": "Synth Bass",
    "25": "Synth Bass",
    "26": "Timpani",
    "27": "Trombone Ensemble",
    "28": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_VS_TSUYOPOKE": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync Lead",
    "3": "Crash Cymbal",
    "4": "Closed Dance HiHat",
    "5": "Open Dance HiHat",
    "6": "Drawbar Organ",
    "7": "Drawbar Organ",
    "8": "Drawbar Organ",
    "9": "Harp",
    "10": "Harp",
    "11": "Harp",
    "12": "Harp",
    "13": "Closed HiHat",
    "14": "Open HiHat",
    "15": "Marimba",
    "16": "Solo Trumpet",
    "17": "Solo Trumpet",
    "18": "Power Snare",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "FM Bass",
    "24": "Snare",
    "25": "Timpani",
    "26": "Trombone Ensemble",
    "27": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_VS_TRAINER": {
    "0": "Trumpet Ensemble",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Chinese Cymbal",
    "4": "Crash Cymbal",
    "5": "Resonant Synth",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "Glockenspiel",
    "9": "Closed HiHat",
    "10": "Open HiHat",
    "11": "Orchestra Hit",
    "12": "Harp",
    "13": "Kick",
    "14": "Power Snare",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "Synth Bass",
    "19": "Timpani",
    "20": "Timpani",
    "21": "Low Floor Tom",
    "22": "High Rack Tom",
    "23": "High Floor Tom",
    "24": "Low Rack Tom",
    "25": "Tuba"
  },
  "WAVE_MUS_WB_VS_SUBWAY_TRAINER": {
    "0": "Trumpet Ensemble",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Crash Cymbal",
    "4": "Drum Loop",
    "5": "Resonant Synth",
    "6": "Resonant Synth",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "Closed HiHat",
    "10": "Open HiHat",
    "11": "Kick",
    "12": "Orchestra Hit",
    "13": "Pizzicato String Ensemble",
    "14": "Snare",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "Synth Bass",
    "19": "Timpani",
    "20": "Timpani",
    "21": "Tuba"
  },
  "WAVE_MUS_WB_VS_GYMLEADER": {
    "0": "Trumpet Ensemble",
    "1": "Trumpet Ensemble",
    "2": "Trumpet Ensemble",
    "3": "Kick",
    "4": "Chinese Cymbal",
    "5": "Crash Cymbal",
    "6": "Synth Bass",
    "7": "Resonant Synth",
    "8": "Resonant Synth",
    "9": "Resonant Synth",
    "10": "Flute",
    "11": "Flute",
    "12": "Timpani",
    "13": "Timpani",
    "14": "Glockenspiel",
    "15": "Closed HiHat",
    "16": "Open HiHat",
    "17": "Orchestra Hit",
    "18": "Roland Orchestra Hit",
    "19": "Sawtooth Lead",
    "20": "Sawtooth Lead",
    "21": "Power Snare",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "Square Lead",
    "25": "Low Floor Tom",
    "26": "High Rack Tom",
    "27": "High Floor Tom",
    "28": "Low Rack Tom"
  },
  "WAVE_MUS_WB_VS_RIVAL": {
    "0": "Accordion",
    "1": "Accordion",
    "2": "Accordion",
    "3": "Trumpet Ensemble",
    "4": "Trumpet Ensemble",
    "5": "Trumpet Ensemble",
    "6": "Kick",
    "7": "Kick + Crash",
    "8": "Castanet",
    "9": "Chinese Cymbal",
    "10": "Crash Cymbal",
    "11": "Guitar String Rattle",
    "12": "Snare",
    "13": "Closed HiHat",
    "14": "Open HiHat",
    "15": "Glockenspiel",
    "16": "Side Stick Clap",
    "17": "Pizzicato String Ensemble",
    "18": "Clap 2",
    "19": "Power Snare",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "Synth Bass Chop",
    "24": "Phaser Lead",
    "25": "Synth Bass",
    "26": "Timpani",
    "27": "Low Floor Tom",
    "28": "High Rack Tom",
    "29": "High Floor Tom",
    "30": "Low Rack Tom",
    "31": "Guitar Wahs"
  },
  "WAVE_MUS_WB_VS_PLASMA": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Chinese Cymbal",
    "3": "Sync lead",
    "4": "Clap/Snare thing",
    "5": "Dubstep Snare",
    "6": "Crash Cymbal",
    "7": "Closed HiHat",
    "8": "Open HiHat",
    "9": "Lead Electric Guitar 1",
    "10": "Lead Electric Guitar 1",
    "11": "Resonant Synth",
    "12": "Resonant Synth",
    "13": "Solo Trumpet",
    "14": "Drawbar Organ",
    "15": "Drawbar Organ",
    "16": "Power Guitar",
    "17": "Power Guitar",
    "18": "Low Electric Guitar",
    "19": "Lead Electric Guitar 2",
    "20": "Lead Electric Guitar 2",
    "21": "Guitar Squeal",
    "22": "Weird Phaser sfx",
    "23": "Disco Strings",
    "24": "Laser FX",
    "25": "Splash Cymbal",
    "26": "String Ensemble",
    "27": "String Ensemble",
    "28": "FM Bass",
    "29": "Snare",
    "30": "Timpani"
  },
  "WAVE_MUS_WB_VS_SHITENNO": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync lead",
    "3": "Clap/Snare thing",
    "4": "Crash Cymbal",
    "5": "Closed HiHat",
    "6": "Open HiHat",
    "7": "Distorted Kick",
    "8": "Distorted Snare",
    "9": "Snare",
    "10": "Flute",
    "11": "Flute",
    "12": "French Horn Ensemble",
    "13": "French Horn Ensemble",
    "14": "Glockenspiel",
    "15": "Trombone Stab",
    "16": "Orchestra Hit",
    "17": "Solo Trumpet",
    "18": "Acoustic Piano",
    "19": "Acoustic Piano",
    "20": "Ride Bell",
    "21": "Roland Orchestra Hit",
    "22": "MG 303 Bass",
    "23": "MG 303 Bass",
    "24": "Sawtooth Lead",
    "25": "Sawtooth Lead",
    "26": "Thin Snare",
    "27": "Slap Bass",
    "28": "String Ensemble",
    "29": "String Ensemble",
    "30": "String Ensemble"
  },
  "WAVE_MUS_WB_VS_CHAMP": {
    "0": "Kick + Crash",
    "1": "Kick",
    "2": "Splash Cymbal",
    "3": "Closed HiHat",
    "4": "Crash Cymbal",
    "5": "Electric Guitar",
    "6": "Electric Guitar",
    "7": "Electric Guitar",
    "8": "Flute",
    "9": "Flute",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "French Horn Ensemble",
    "13": "Clap",
    "14": "Trombone Stab",
    "15": "Orchestra Hit (Major)",
    "16": "Orchestra Hit (Minor)",
    "17": "Trinity Orchestra Hit",
    "18": "Open HiHat",
    "19": "Ride Bell",
    "20": "Power Snare",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "Synth Bass",
    "26": "Timpani",
    "27": "Timpani",
    "28": "Trombone Ensemble",
    "29": "Trombone Ensemble",
    "30": "Trumpet Ensemble",
    "31": "Trumpet Ensemble",
    "32": "Trumpet Ensemble",
    "33": "Marimba",
    "34": "Marimba"
  },
  "WAVE_MUS_WB_VS_N": {
    "0": "Kick",
    "1": "Sync lead",
    "2": "Crash Cymbal",
    "3": "Closed HiHat",
    "4": "Open HiHat",
    "5": "Snare",
    "6": "Flute",
    "7": "Flute",
    "8": "Glockenspiel",
    "9": "Brass Ensemble",
    "10": "Solo Trumpet",
    "11": "Side Stick",
    "12": "Roland Orchestra Hit",
    "13": "MG 303 Bass",
    "14": "MG 303 Bass",
    "15": "Sawtooth Lead",
    "16": "Rimshot Snare",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "Synth Bass"
  },
  "WAVE_MUS_WB_VS_N_2": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Choir",
    "3": "Choir",
    "4": "Choir",
    "5": "Clock 1",
    "6": "Clock 2",
    "7": "Sync lead",
    "8": "Clap/Snare thing",
    "9": "Crash Cymbal",
    "10": "Closed HiHat",
    "11": "Open HiHat",
    "12": "Sawtooth Lead",
    "13": "Snare",
    "14": "Flute",
    "15": "Flute",
    "16": "French Horn Ensemble",
    "17": "French Horn Ensemble",
    "18": "Glockenspiel",
    "19": "Harpsichord",
    "20": "Orchestra Hit",
    "21": "Brass Ensemble",
    "22": "Pipe Organ",
    "23": "Pipe Organ",
    "24": "Solo Trumpet",
    "25": "Steel Drum",
    "26": "Gunshot",
    "27": "FM Bass",
    "28": "Synth Bass",
    "29": "Timpani",
    "30": "Trombone Ensemble",
    "31": "White Noise/Static"
  },
  "WAVE_MUS_WB_VS_G_CIS": {
    "0": "High Female Choir",
    "1": "Trumpet",
    "2": "Trumpet",
    "3": "Breath",
    "4": "Chinese Cymbal",
    "5": "\"tsis\" vocal (male)",
    "6": "Choir",
    "7": "Choir",
    "8": "Choir",
    "9": "Gong",
    "10": "\"eh\" vocal (male)",
    "11": "Roland Taiko",
    "12": "Music Box",
    "13": "Low Taiko",
    "14": "Timpani",
    "15": "Timpani",
    "16": "Timpani",
    "17": "\"Ghe\" vocal (male)",
    "18": "\"Ghe\" vocal (female)",
    "19": "Harp",
    "20": "\"tsis\" vocal (female)",
    "21": "Trombone Ensemble",
    "22": "Trombone Ensemble",
    "23": "Taiko 1",
    "24": "Taiko 2"
  },
  "WAVE_MUS_WB_VS_SHIN": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync lead",
    "3": "Crash Cymbal",
    "4": "Closed HiHat",
    "5": "Open HiHat",
    "6": "Flute",
    "7": "Flute",
    "8": "French Horn Rip 1",
    "9": "French Horn Rip 2",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "Glockenspiel",
    "13": "Trombone Stab",
    "14": "Oboe",
    "15": "Oboe",
    "16": "Orchestra Hit",
    "17": "Solo Trumpet",
    "18": "Acoustic Piano",
    "19": "Acoustic Piano",
    "20": "Flame SFX",
    "21": "Ride Bell",
    "22": "Drum Roll",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "Synth Bass",
    "27": "Timpani",
    "28": "Timpani",
    "29": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_VS_MU": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync lead",
    "3": "Crash Cymbal",
    "4": "Closed HiHat",
    "5": "Open HiHat",
    "6": "Flute",
    "7": "Flute",
    "8": "French Horn Rip 1",
    "9": "French Horn Rip 2",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "Glockenspiel",
    "13": "Trombone Stab",
    "14": "Oboe",
    "15": "Oboe",
    "16": "Orchestra Hit",
    "17": "Solo Trumpet",
    "18": "Acoustic Piano",
    "19": "Acoustic Piano",
    "20": "Ride Bell",
    "21": "Drum Roll",
    "22": "String Ensemble",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "Synth Bass",
    "26": "Timpani",
    "27": "Timpani",
    "28": "Trombone Ensemble",
    "29": "Zap SFX"
  },
  "WAVE_MUS_WB_VS_RAI": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Sync lead",
    "3": "Crash Cymbal",
    "4": "Closed HiHat",
    "5": "Open HiHat",
    "6": "Flute",
    "7": "Flute",
    "8": "French Horn Rip 1",
    "9": "French Horn Rip 2",
    "10": "French Horn Ensemble",
    "11": "French Horn Ensemble",
    "12": "Glockenspiel",
    "13": "Trombone Stab",
    "14": "Oboe",
    "15": "Oboe",
    "16": "Orchestra Hit",
    "17": "Solo Trumpet",
    "18": "Acoustic Piano",
    "19": "Acoustic Piano",
    "20": "Ride Bell",
    "21": "Slap Bass",
    "22": "Drum Roll",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "Synth Bass",
    "27": "Timpani",
    "28": "Timpani",
    "29": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_VS_MOVEPOKE": {
    "0": "Kick",
    "1": "Kick + Crash",
    "2": "Chinese Cymbal",
    "3": "Car Crash",
    "4": "Sync lead",
    "5": "Clap/Snare thing",
    "6": "Crash Cymbal",
    "7": "Closed HiHat",
    "8": "Open HiHat",
    "9": "Distorted Kick",
    "10": "Distorted Snare",
    "11": "Snare",
    "12": "Timpani",
    "13": "Timpani",
    "14": "Timpani",
    "15": "Orchestra Hit (Minor)",
    "16": "Car Stop",
    "17": "Solo Trumpet",
    "18": "Acoustic Piano",
    "19": "Acoustic Piano",
    "20": "Roland Orchestra Hit",
    "21": "MG 303 Bass",
    "22": "MG 303 Bass",
    "23": "Sawtooth Lead",
    "24": "Sawtooth Lead",
    "25": "Thin Snare",
    "26": "Power Snare",
    "27": "Drum Roll",
    "28": "Splash Cymbal",
    "29": "String Ensemble",
    "30": "Synth Bass"
  },
  "WAVE_MUS_WB_VS_SHIRONA": {
    "0": "Kick",
    "1": "Dance Kick",
    "2": "Splash Cymbal",
    "3": "Closed HiHat",
    "4": "Crash Cymbal",
    "5": "Electric Guitar",
    "6": "Electric Guitar",
    "7": "Electric Guitar",
    "8": "Electric Guitar",
    "9": "Electric Guitar",
    "10": "Electric Piano",
    "11": "Electric Piano",
    "12": "Yamaha Kick",
    "13": "Sawtooth Lead",
    "14": "Snare",
    "15": "French Horn",
    "16": "French Horn",
    "17": "Timpani 1",
    "18": "Timpani 1",
    "19": "Choir",
    "20": "Orchestra Hit 1",
    "21": "Orchestra Hit 2",
    "22": "Orchestra Hit 3",
    "23": "Orchestra Hit 4",
    "24": "Open HiHat",
    "25": "Drawbar Organ",
    "26": "Drawbar Organ",
    "27": "Choir",
    "28": "String Ensemble",
    "29": "String Ensemble",
    "30": "String Ensemble",
    "31": "String Ensemble",
    "32": "Wah Bass",
    "33": "MG 303 Bass",
    "34": "Timpani 2",
    "35": "Timpani 2",
    "36": "Trombone",
    "37": "Trombone",
    "38": "Trombone",
    "39": "Violin",
    "40": "Violin",
    "41": "Violin",
    "42": "Whistle"
  },
  "WAVE_MUS_WB_BATTLEPINCH": {
    "0": "Chinese Cymbal",
    "1": "Crash Cymbal",
    "2": "Drawbar Organ",
    "3": "Drawbar Organ",
    "4": "Drawbar Organ",
    "5": "Fretless Bass",
    "6": "Fretless Bass",
    "7": "Kick",
    "8": "Orchestra Hit",
    "9": "Orchestra Hit",
    "10": "Orchestra Hit",
    "11": "Power Snare",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "Low Floor Tom",
    "16": "High Rack Tom",
    "17": "High Floor Tom",
    "18": "Low Rack Tom"
  },
  "WAVE_MUS_WB_BATTLESUPERIOR": {
    "0": "Trumpet Ensemble",
    "1": "Trumpet Ensemble",
    "2": "Solo Cello",
    "3": "Orchestral Cymbal",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "Solo Trumpet",
    "8": "Rimshot Snare",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "Timpani",
    "13": "Trombone Ensemble"
  },
  "WAVE_MUS_WB_WIN1": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "Orchestral Cymbal",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "Flute",
    "7": "Flute",
    "8": "Flute",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Timpani",
    "15": "Timpani",
    "16": "Trumpet Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Vibraphone",
    "20": "Vibraphone",
    "21": "Vibraphone"
  },
  "WAVE_MUS_WB_WIN2": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Clarinet",
    "3": "Orchestral Cymbal",
    "4": "Flute",
    "5": "Flute",
    "6": "Flute",
    "7": "Orchestral Snare",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "Timpani",
    "12": "Timpani",
    "13": "Trombone Ensemble",
    "14": "Trombone Ensemble",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_WIN3": {
    "0": "Solo Cello",
    "1": "Solo Cello",
    "2": "Clarinet",
    "3": "Clarinet",
    "4": "Clarinet",
    "5": "Orchestral Cymbal",
    "6": "Flute",
    "7": "Flute",
    "8": "Flute",
    "9": "Orchestral Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Timpani",
    "15": "Trombone Ensemble",
    "16": "Trombone Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_WIN4": {
    "0": "Staccato Trumpet",
    "1": "Low Strings",
    "2": "Spiccato Strings",
    "3": "Crash Cymbal",
    "4": "Suspended Cymbal",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "Harp",
    "10": "Harp",
    "11": "Harp",
    "12": "Staccato Trombone",
    "13": "Solo Trumpet",
    "14": "Flute",
    "15": "Flute",
    "16": "Drum Roll",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Timpani",
    "20": "Trumpet Ensemble",
    "21": "Trumpet Ensemble",
    "22": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_WIN5": {
    "0": "Orchestral Cymbal",
    "1": "French Horn Ensemble",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "Harp",
    "6": "Harp",
    "7": "Harp",
    "8": "Harp",
    "9": "Rimshot Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Timpani",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Trumpet Ensemble",
    "18": "Tubular Bells",
    "19": "Tubular Bells"
  },
  "WAVE_MUS_WB_WIFI_ACCESS": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Upright Bass",
    "3": "Acoustic Kick",
    "4": "Shaker",
    "5": "Electric Piano",
    "6": "Electric Piano",
    "7": "Marimba",
    "8": "Marimba",
    "9": "Marimba",
    "10": "Rim Hit",
    "11": "Vibraphone",
    "12": "Vibraphone",
    "13": "Vibraphone"
  },
  "WAVE_MUS_WB_WIFI_PRESENT": {
    "0": "Upright Bass",
    "1": "Kick",
    "2": "Compressed Kick",
    "3": "Crash Cymbal",
    "4": "Rhode Piano",
    "5": "Rhode Piano",
    "6": "Clap",
    "7": "Closed Acoustic HiHat",
    "8": "Open Acoustic HiHat",
    "9": "Organ",
    "10": "Organ",
    "11": "Organ",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Acoustic Piano",
    "15": "Acoustic Piano",
    "16": "Acoustic Piano",
    "17": "Pizzicato String Ensemble",
    "18": "Pizzicato String Ensemble",
    "19": "Pizzicato String Ensemble",
    "20": "Pizzicato String Ensemble",
    "21": "Pizzicato String Ensemble",
    "22": "Slap Bass",
    "23": "Orchestral Snare",
    "24": "Analogue (808) Snare",
    "25": "Power Snare",
    "26": "String Ensemble",
    "27": "String Ensemble",
    "28": "String Ensemble",
    "29": "String Ensemble",
    "30": "String Ensemble",
    "31": "Synth Bass",
    "32": "Synth Bass",
    "33": "Marimba",
    "34": "Marimba"
  },
  "WAVE_MUS_WB_GAME_SYNC": {
    "0": "Rhode Piano",
    "1": "Rhode Piano",
    "2": "Acoustic Piano",
    "3": "Acoustic Piano",
    "4": "Closed HiHat",
    "5": "Analog Kick 1",
    "6": "Percussive Organ"
  },
  "WAVE_MUS_WB_GLTERMINAL": {
    "0": "Acoustic Piano",
    "1": "Acoustic Piano",
    "2": "Acoustic Kick",
    "3": "Chinese Cymbal",
    "4": "Drawbar Organ",
    "5": "Drawbar Organ",
    "6": "Drawbar Organ",
    "7": "Electric Piano",
    "8": "Electric Piano",
    "9": "Acoustic Piano",
    "10": "Acoustic Piano",
    "11": "Acoustic Piano",
    "12": "Acoustic Piano",
    "13": "Harp",
    "14": "Harp",
    "15": "Harp",
    "16": "Closed Acoustic HiHat",
    "17": "Flute",
    "18": "Flute",
    "19": "Flute",
    "20": "Flute",
    "21": "Reverse Cymbal",
    "22": "Orchestra Snare",
    "23": "String Ensemble",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "String Ensemble",
    "27": "Synth Bass",
    "28": "Synth Bass"
  },
  "WAVE_MUS_WB_GURUGURU": {
    "0": "Accordion",
    "1": "Accordion",
    "2": "Kick",
    "3": "High Bongo",
    "4": "Crash Cymbal",
    "5": "Orchestral Cymbal",
    "6": "Hand Clap",
    "7": "Open High Conga",
    "8": "Open Acoustic HiHat",
    "9": "Marimba",
    "10": "Marimba",
    "11": "Muted High Conga",
    "12": "Acoustic Piano",
    "13": "Acoustic Piano",
    "14": "Acoustic Piano",
    "15": "Acoustic Piano",
    "16": "Acoustic Piano",
    "17": "Ride Bell",
    "18": "Orchestral Snare",
    "19": "Analogue (808) Snare",
    "20": "String Ensemble",
    "21": "String Ensemble",
    "22": "String Ensemble",
    "23": "Synth Bass",
    "24": "Synth Bass",
    "25": "Tambourine",
    "26": "Low Floor Tom",
    "27": "High Rack Tom",
    "28": "High Floor Tom",
    "29": "Low Rack Tom",
    "30": "Triangle",
    "31": "Solo Violin",
    "32": "Solo Violin"
  },
  "WAVE_MUS_WB_GTS": {
    "0": "Clarinet",
    "1": "Clarinet",
    "2": "Orchestral Cymbal",
    "3": "French Horn Ensemble",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "Oboe",
    "7": "Oboe",
    "8": "Oboe",
    "9": "Flute",
    "10": "Flute",
    "11": "Flute",
    "12": "Orchestra Snare",
    "13": "String Ensemble",
    "14": "String Ensemble",
    "15": "String Ensemble",
    "16": "String Ensemble",
    "17": "Timpani",
    "18": "Timpani",
    "19": "Timpani",
    "20": "Trumpet Ensemble",
    "21": "Trumpet Ensemble",
    "22": "Trumpet Ensemble",
    "23": "Xylophone",
    "24": "Xylophone",
    "25": "Xylophone"
  },
  "WAVE_MUS_WB_WCS": {
    "0": "Solo Cello",
    "1": "Orchestral Cymbal",
    "2": "French Horn Ensemble",
    "3": "French Horn Ensemble",
    "4": "Flute",
    "5": "Flute",
    "6": "Flute",
    "7": "Orchestral Snare",
    "8": "String Ensemble",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "Timpani",
    "13": "Trombone Ensemble",
    "14": "Trombone Ensemble",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Xylophone",
    "18": "Xylophone",
    "19": "Xylophone"
  },
  "WAVE_MUS_WB_E_SHIRONA": {
    "0": "Acoustic Piano",
    "1": "Acoustic Piano",
    "2": "Acoustic Piano",
    "3": "Acoustic Piano",
    "4": "Acoustic Piano",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano"
  },
  "WAVE_MUS_WB_E_FRIEND": {
    "0": "Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "Fretless Bass",
    "4": "Fretless Bass",
    "5": "Acoustic Piano",
    "6": "Acoustic Piano",
    "7": "Acoustic Piano",
    "8": "Closed Acoustic HiHat",
    "9": "Open Acoustic HiHat",
    "10": "Nylon String Guitar",
    "11": "Nylon String Guitar",
    "12": "Nylon String Guitar",
    "13": "Flute",
    "14": "Flute",
    "15": "Flute",
    "16": "Power Snare",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "String Ensemble",
    "20": "String Ensemble",
    "21": "Low Floor Tom",
    "22": "High Floor Tom",
    "23": "Low Rack Tom",
    "24": "Trumpet Ensemble",
    "25": "Trumpet Ensemble",
    "26": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_E_SOUND_DESIGNER": {
    "0": "Kick",
    "1": "Chinese Cymbal",
    "2": "Crash Cymbal",
    "3": "Marschall Guitar",
    "4": "Marschall Guitar",
    "5": "Marschall Guitar",
    "6": "Marschall Guitar",
    "7": "Open Acoustic HiHat",
    "8": "Slap Bass",
    "9": "Power Snare",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "String Ensemble",
    "14": "Low Floor Tom",
    "15": "High Rack Tom",
    "16": "High Floor Tom",
    "17": "Low Rack Tom",
    "18": "Trumpet Ensemble",
    "19": "Trumpet Ensemble",
    "20": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_VS_WCS": {
    "0": "Solo Cello",
    "1": "Male Choir",
    "2": "Male Choir",
    "3": "Male Choir",
    "4": "Suspended Cymbal",
    "5": "Orchestral Cymbal",
    "6": "Drum Loop",
    "7": "French Horn Ensemble",
    "8": "French Horn Ensemble",
    "9": "French Horn Ensemble",
    "10": "Closed Electric HiHat",
    "11": "Open Electric HiHat",
    "12": "Electric Kick",
    "13": "Orchestra Hit Minor",
    "14": "Electric Snare",
    "15": "Orchestral Snare",
    "16": "String Ensemble",
    "17": "String Ensemble",
    "18": "String Ensemble",
    "19": "Synth Bass",
    "20": "Timpani",
    "21": "Trombone Ensemble",
    "22": "Trombone Ensemble",
    "23": "Trumpet Ensemble",
    "24": "Trumpet Ensemble"
  },
  "WAVE_MUS_WB_E_LEGEND_COME_B": {
    "0": "Dragon Growl",
    "1": "Metal SFX (Zekrom Cry)",
    "2": "Solo Cello",
    "3": "Orchestral Cymbal",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "Orchestral Snare",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Trumpet Ensemble",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Low Wind"
  },
  "WAVE_MUS_WB_E_LEGEND_COME_W": {
    "0": "Dragon Growl",
    "1": "Dog SFX (Reshiram Cry)",
    "2": "Solo Cello",
    "3": "Orchestral Cymbal",
    "4": "French Horn Ensemble",
    "5": "French Horn Ensemble",
    "6": "French Horn Ensemble",
    "7": "French Horn Ensemble",
    "8": "Orchestral Snare",
    "9": "String Ensemble",
    "10": "String Ensemble",
    "11": "String Ensemble",
    "12": "String Ensemble",
    "13": "Timpani",
    "14": "Trumpet Ensemble",
    "15": "Trumpet Ensemble",
    "16": "Trumpet Ensemble",
    "17": "Low Wind"
  },
  "WAVE_MUS_WB_N_ROOM": {
    "0": "Music Box",
    "1": "Music Box",
    "2": "Music Box"
  },
  "WAVE_MUS_WB_E_EPIROGUE": {
    "0": "ocean sfx",
    "1": "ocean sfx",
    "2": "ocean sfx",
    "3": "electricity sfx"
  },
  "WAVE_MUS_WB_GF_LOGO": {
    "0": "\"Ship\" Synth Ambience",
    "1": "Swoosh (Starship)",
    "2": "Shattering Noise",
    "3": "Reverse Chord",
    "4": "Transition Effect"
  },
  "WAVE_MUS_WB_PALPARK_NARC": {
    "0": "Kick",
    "1": "Drawbar Organ",
    "2": "Drawbar Organ",
    "3": "Drawbar Organ",
    "4": "Rhode Piano",
    "5": "Rhode Piano",
    "6": "Clap",
    "7": "Tambourine"
  },
  "WAVE_MUS_WB_MSL_DL_DUMMY_01": {
    "0": "Upright Bass",
    "1": "Upright Bass",
    "2": "Compressed Kick",
    "3": "Dance Kick",
    "4": "Shaker",
    "5": "Clarinet",
    "6": "Clarinet",
    "7": "Clarinet",
    "8": "Clean Guitar",
    "9": "Clean Guitar",
    "10": "Clean Guitar",
    "11": "Clean Guitar",
    "12": "Crash Cymbal",
    "13": "Marschall Guitar",
    "14": "Marschall Guitar",
    "15": "Marschall Guitar",
    "16": "Marschall Guitar",
    "17": "Fretless Bass",
    "18": "Fretless Bass",
    "19": "Rhode Piano",
    "20": "Rhode Piano",
    "21": "French Horn Ensemble",
    "22": "French Horn Ensemble",
    "23": "French Horn Ensemble",
    "24": "Acoustic Piano",
    "25": "Acoustic Piano",
    "26": "Acoustic Piano",
    "27": "Acoustic Piano",
    "28": "Acoustic Piano",
    "29": "Clap",
    "30": "Harp",
    "31": "Harp",
    "32": "Harp",
    "33": "Open High Conga",
    "34": "Closed Acoustic HiHat",
    "35": "Open Acoustic HiHat",
    "36": "Marimba",
    "37": "Marimba",
    "38": "Marimba",
    "39": "\"door creaking\"???",
    "40": "\"door creaking\"???",
    "41": "\"door creaking\"???",
    "42": "\"door creaking\"???",
    "43": "Muted High Conga",
    "44": "Nylon String Guitar",
    "45": "Nylon String Guitar",
    "46": "Nylon String Guitar",
    "47": "Nylon String Guitar",
    "48": "Orchestra Hit",
    "49": "Orchestra Hit",
    "50": "Percussive Organ",
    "51": "Percussive Organ",
    "52": "Percussive Organ",
    "53": "Flute",
    "54": "Flute",
    "55": "Flute",
    "56": "Flute",
    "57": "Pizzicato String Ensemble",
    "58": "Pizzicato String Ensemble",
    "59": "Pizzicato String Ensemble",
    "60": "Pizzicato String Ensemble",
    "61": "Pizzicato String Ensemble",
    "62": "Reverse Cymbal",
    "63": "Side Stick",
    "64": "Slap Bass",
    "65": "Orchestral Snare",
    "66": "Analogue (808) Snare",
    "67": "Orchestral Snare",
    "68": "Power Snare",
    "69": "String Ensemble",
    "70": "String Ensemble",
    "71": "String Ensemble",
    "72": "String Ensemble",
    "73": "Tambourine",
    "74": "Timpani",
    "75": "Timpani",
    "76": "Timpani",
    "77": "Low Floor Tom",
    "78": "High Rack Tom",
    "79": "High Floor Tom",
    "80": "Low Rack Tom",
    "81": "Triangle",
    "82": "Trumpet Ensemble",
    "83": "Trumpet Ensemble",
    "84": "Trumpet Ensemble",
    "85": "Tubular Bells",
    "86": "Tubular Bells",
    "87": "Vibraphone",
    "88": "Vibraphone"
  },
  "WAVE_MUS_WB_MSL_DL_DUMMY_03": {
    "0": "Keyboard Stab (?)",
    "1": "Sampled Drum Pattern",
    "2": "Cuica",
    "3": "Whistle",
    "4": "Fretless Bass",
    "5": "Fretless Bass",
    "6": "Rhode Piano",
    "7": "Rhode Piano",
    "8": "Clap",
    "9": "Closed Acoustic HiHat",
    "10": "Open Acoustic HiHat",
    "11": "Acoustic Kick",
    "12": "\"door creaking\"???",
    "13": "\"door creaking\"???",
    "14": "\"door creaking\"???",
    "15": "\"door creaking\"???",
    "16": "Nylon String Guitar",
    "17": "Nylon String Guitar",
    "18": "Nylon String Guitar",
    "19": "Percussive Organ",
    "20": "Percussive Organ",
    "21": "Percussive Organ",
    "22": "Rim Hit",
    "23": "Power Snare",
    "24": "String Ensemble",
    "25": "String Ensemble",
    "26": "String Ensemble",
    "27": "String Ensemble",
    "28": "Synth Bass",
    "29": "Synth Bass",
    "30": "Tambourine",
    "31": "Low Floor Tom",
    "32": "High Rack Tom",
    "33": "High Floor Tom",
    "34": "Low Rack Tom",
    "35": "Vibraphone",
    "36": "Vibraphone",
    "37": "Vibraphone"
  }
};
