const EXACT = {
  SEQ_BGM_DUMMY: ["Unused / test background music", ""],
  SEQ_BGM_SILENCE_FIELD: ["Field silence", ""],
  SEQ_BGM_SILENCE_DUNGEON: ["Dungeon silence", ""],
  SEQ_BGM_TITLE: ["Title screen", ""],
  SEQ_BGM_TITLE01: ["Title screen intro", ""],
  SEQ_BGM_OPENING_TITLE_B: ["Opening title sequence", "Black version"],
  SEQ_BGM_OPENING_TITLE_W: ["Opening title sequence", "White version"],
  SEQ_BGM_POKEMON_THEME: ["Pokémon opening theme", ""],
  SEQ_BGM_STARTING: ["Professor Juniper introduction", "Part 1"],
  SEQ_BGM_STARTING2: ["Professor Juniper introduction", "Part 2"],
  SEQ_BGM_SHINKA: ["Evolution", ""],
  SEQ_BGM_KOUKAN: ["Pokémon trade", ""],
  SEQ_BGM_BICYCLE: ["Riding the bicycle", ""],
  SEQ_BGM_NAMINORI: ["Surfing", ""],
  SEQ_BGM_DIVING: ["Diving", ""],
  SEQ_BGM_E_DENDOUIRI: ["Hall of Fame induction", ""],
  SEQ_BGM_ENDING: ["Ending credits", ""],
  SEQ_BGM_ENDING2: ["Ending transition", ""],

  SEQ_BGM_T_01: ["Nuvema Town", ""],
  SEQ_BGM_T_02: ["Accumula Town", ""],
  SEQ_BGM_T_03: ["Anville Town", ""],
  SEQ_BGM_T_04: ["Lacunosa Town", ""],
  SEQ_BGM_T_05_SP: ["Undella Town", "Spring"],
  SEQ_BGM_T_05_SU: ["Undella Town", "Summer"],
  SEQ_BGM_T_05_AU: ["Undella Town", "Autumn"],
  SEQ_BGM_T_05_WI: ["Undella Town", "Winter"],

  SEQ_BGM_C_01: ["Striaton City", ""],
  SEQ_BGM_C_02: ["Nacrene City", ""],
  SEQ_BGM_C_03: ["Castelia City", ""],
  SEQ_BGM_C_04: ["Nimbasa City", ""],
  SEQ_BGM_C_05: ["Driftveil City", ""],
  SEQ_BGM_C_06: ["Mistralton City", ""],
  SEQ_BGM_C_07: ["Icirrus City", ""],
  SEQ_BGM_C_08_B: ["Opelucid City", "Black version"],
  SEQ_BGM_C_08_W: ["Opelucid City", "White version"],
  SEQ_BGM_C_10_B: ["Black City / White Forest", "Black City (Black version)"],
  SEQ_BGM_C_10_W: ["Black City / White Forest", "White Forest (White version)"],

  SEQ_BGM_R_A: ["Route 1", ""],
  SEQ_BGM_R_B_SP: ["Routes 2–3 / Skyarrow Bridge exterior", "Spring"],
  SEQ_BGM_R_B_SU: ["Routes 2–3 / Skyarrow Bridge exterior", "Summer"],
  SEQ_BGM_R_B_AU: ["Routes 2–3 / Skyarrow Bridge exterior", "Autumn"],
  SEQ_BGM_R_B_WI: ["Routes 2–3 / Skyarrow Bridge exterior", "Winter"],
  SEQ_BGM_R_C_SP: ["Route 4 area", "Spring"],
  SEQ_BGM_R_C_SU: ["Route 4 area", "Summer"],
  SEQ_BGM_R_C_AU: ["Route 4 area", "Autumn"],
  SEQ_BGM_R_C_WI: ["Route 4 area", "Winter"],
  SEQ_BGM_R_D_SP: ["Mid-Unova routes", "Spring"],
  SEQ_BGM_R_D_SU: ["Mid-Unova routes", "Summer"],
  SEQ_BGM_R_D_AU: ["Mid-Unova routes", "Autumn"],
  SEQ_BGM_R_D_WI: ["Mid-Unova routes", "Winter"],
  SEQ_BGM_R_E_SP: ["Eastern Unova routes", "Spring"],
  SEQ_BGM_R_E_SU: ["Eastern Unova routes", "Summer"],
  SEQ_BGM_R_E_AU: ["Eastern Unova routes", "Autumn"],
  SEQ_BGM_R_E_WI: ["Eastern Unova routes", "Winter"],
  SEQ_BGM_R_F: ["Route 10", ""],

  SEQ_BGM_H_01: ["Skyarrow Bridge", ""],
  SEQ_BGM_H_02: ["Driftveil Drawbridge", ""],
  SEQ_BGM_H_03: ["Tubeline Bridge", ""],
  SEQ_BGM_H_04: ["Village Bridge", ""],
  SEQ_BGM_H_05: ["Marvelous Bridge", ""],
  SEQ_BGM_POKECEN: ["Pokémon Center", ""],
  SEQ_BGM_FS: ["Indoor facility", ""],
  SEQ_BGM_GYM: ["Pokémon Gym", ""],
  SEQ_BGM_GYM_C05: ["Gym variation", ""],
  SEQ_BGM_LABO: ["Professor Juniper's laboratory", ""],
  SEQ_BGM_GATE: ["Route gate", ""],
  SEQ_BGM_GEAR_STATION: ["Gear Station", ""],
  SEQ_BGM_BATTLE_SUBWAY: ["Battle Subway", ""],
  SEQ_BGM_PALPARK: ["Entralink", ""],
  SEQ_BGM_PLEASURE_BOAT: ["Royal Unova", ""],
  SEQ_BGM_PALACE: ["Royal / palace interior", "Part 1"],
  SEQ_BGM_PALACE2: ["Royal / palace interior", "Part 2"],
  SEQ_BGM_UNITED_NATIONS: ["Unity Tower", ""],
  SEQ_BGM_POKEMON_LEAGUE: ["Pokémon League", "Outside"],
  SEQ_BGM_POKEMON_LEAGUE2: ["Pokémon League", "Interior"],
  SEQ_BGM_N_CASTLE_BRIDGE: ["N's Castle", "Bridge"],
  SEQ_BGM_N_CASTLE: ["N's Castle", "Interior"],

  SEQ_BGM_D_01: ["Dreamyard / forest dungeon area", ""],
  SEQ_BGM_D_02: ["Wellspring Cave", ""],
  SEQ_BGM_D_03: ["Chargestone Cave", ""],
  SEQ_BGM_D_04: ["Mistralton Cave", ""],
  SEQ_BGM_D_05: ["Twist Mountain", ""],
  SEQ_BGM_D_06: ["Dragonspiral Tower", ""],
  SEQ_BGM_D_07: ["Abyssal Ruins / late-game dungeon", ""],
  SEQ_BGM_D_CHAMPROAD: ["Victory Road", ""],

  SEQ_BGM_E_TSURETEKE1: ["Story scene – being led somewhere", "Part 1"],
  SEQ_BGM_E_TSURETEKE2: ["Story scene – being led somewhere", "Part 2"],
  SEQ_BGM_E_RIVAL: ["Cheren / rival story scene", ""],
  SEQ_BGM_E_SUPPORT: ["Supportive story scene", ""],
  SEQ_BGM_E_DOCTOR: ["Pokémon healing / doctor scene", "Part 1"],
  SEQ_BGM_E_DOCTOR2: ["Pokémon healing / doctor scene", "Part 2"],
  SEQ_BGM_E_PLASMA: ["Team Plasma story scene", ""],
  SEQ_BGM_E_N: ["N story scene", ""],
  SEQ_BGM_E_SAGE: ["Seven Sages story scene", ""],
  SEQ_BGM_E_G_CIS: ["Ghetsis story scene", ""],
  SEQ_BGM_E_GL_UNION: ["Global Link / communication scene", ""],
  SEQ_BGM_E_INISHIE: ["Ancient / ruins story scene", ""],
  SEQ_BGM_E_EMOTION: ["Emotional story scene", ""],
  SEQ_BGM_E_TROUBLE: ["Trouble / danger story scene", ""],
  SEQ_BGM_E_LAST: ["Final story scene", ""],
  SEQ_BGM_E_HANDSOME: ["Looker story scene", ""],
  SEQ_BGM_E_CHAMPION: ["Champion story scene", ""],
  SEQ_BGM_E_OPENING: ["Opening story sequence", ""],
  SEQ_BGM_E_KANRANSYA: ["Nimbasa Ferris wheel", ""],
  SEQ_BGM_E_N_CASTLE: ["N's Castle story scene", ""],
  SEQ_BGM_E_LEGEND_BORN_B: ["Legendary dragon awakening", "Black version"],
  SEQ_BGM_E_LEGEND_BORN_W: ["Legendary dragon awakening", "White version"],
  SEQ_BGM_E_LEGEND_COME_B: ["Legendary dragon arrival", "Black version"],
  SEQ_BGM_E_LEGEND_COME_W: ["Legendary dragon arrival", "White version"],

  SEQ_BGM_MSL_FIELD: ["Pokémon Musical", "Lobby"],
  SEQ_BGM_MSL_DRESSUP: ["Pokémon Musical", "Dress-up"],
  SEQ_BGM_MSL_BEFORE: ["Pokémon Musical", "Before show"],
  SEQ_BGM_MSL_01: ["Pokémon Musical", "Show 1"],
  SEQ_BGM_MSL_02: ["Pokémon Musical", "Show 2"],
  SEQ_BGM_MSL_03: ["Pokémon Musical", "Show 3"],
  SEQ_BGM_MSL_04: ["Pokémon Musical", "Show 4"],

  SEQ_BGM_VS_NORAPOKE: ["Battle – wild Pokémon", "Normal"],
  SEQ_BGM_VS_TSUYOPOKE: ["Battle – wild Pokémon", "Strong / special encounter"],
  SEQ_BGM_VS_TRAINER: ["Battle – Trainer", ""],
  SEQ_BGM_VS_SUBWAY_TRAINER: ["Battle – Subway Trainer", ""],
  SEQ_BGM_VS_GYMLEADER: ["Battle – Gym Leader", ""],
  SEQ_BGM_VS_RIVAL: ["Battle – Cheren / rival", ""],
  SEQ_BGM_VS_PLASMA: ["Battle – Team Plasma", ""],
  SEQ_BGM_VS_SHITENNO: ["Battle – Elite Four", ""],
  SEQ_BGM_VS_CHAMP: ["Battle – Champion", ""],
  SEQ_BGM_VS_N: ["Battle – N", "First version"],
  SEQ_BGM_VS_N_2: ["Battle – N", "Final version"],
  SEQ_BGM_VS_G_CIS: ["Battle – Ghetsis", ""],
  SEQ_BGM_VS_SHIN: ["Battle – legendary Pokémon", "Group 1"],
  SEQ_BGM_VS_MU: ["Battle – legendary Pokémon", "Group 2"],
  SEQ_BGM_VS_RAI: ["Battle – legendary Pokémon", "Group 3"],
  SEQ_BGM_VS_MOVEPOKE: ["Battle – roaming Pokémon", ""],
  SEQ_BGM_VS_SETPOKE: ["Battle – stationary Pokémon", ""],
  SEQ_BGM_VS_SHIRONA: ["Battle – Cynthia", ""],
  SEQ_BGM_BATTLEPINCH: ["Battle – low HP", ""],
  SEQ_BGM_BATTLESUPERIOR: ["Battle – opponent's last Pokémon", ""],
  SEQ_BGM_WIFI_ACCESS: ["Nintendo Wi-Fi Connection", "Connecting"],
  SEQ_BGM_WIFI_PRESENT: ["Nintendo Wi-Fi Connection", "Connected"],
  SEQ_BGM_GAME_SYNC: ["Game Sync", ""],
  SEQ_BGM_GLTERMINAL: ["Global Terminal", ""],
  SEQ_BGM_GURUGURU: ["Spin Trade", ""],
  SEQ_BGM_GTS: ["GTS", ""],
  SEQ_BGM_WCS: ["Wireless / competition lobby", ""],
  SEQ_BGM_E_SHIRONA: ["Cynthia encounter", ""],
  SEQ_BGM_E_FRIEND: ["Friend / multiplayer scene", ""],
  SEQ_BGM_E_SOUND_DESIGNER: ["Game Freak sound designer room", ""],
  SEQ_BGM_VS_TRAINER_M: ["Battle – Trainer", "Multiplayer variation"],
  SEQ_BGM_VS_TRAINER_S: ["Battle – Trainer", "Special variation"],
  SEQ_BGM_VS_WCS: ["Battle – wireless competition", ""],
  SEQ_BGM_VS_TRAINER_WIFI: ["Battle – Wi-Fi Trainer", ""],
  SEQ_BGM_N_ROOM: ["N's room", ""],
  SEQ_BGM_E_EPIROGUE: ["Epilogue", "Black version / common"],
  SEQ_BGM_E_EPIROGUE_W: ["Epilogue", "White version"],
  SEQ_BGM_GF_LOGO: ["Game Freak logo", ""],
  SEQ_BGM_END: ["Music data end marker", ""]
};

const WIN_NAMES = {
  SEQ_BGM_WIN1: "Victory – wild Pokémon",
  SEQ_BGM_WIN2: "Victory – Trainer",
  SEQ_BGM_WIN3: "Victory – Gym Leader",
  SEQ_BGM_WIN4: "Victory – Team Plasma",
  SEQ_BGM_WIN5: "Victory – major battle",
  SEQ_BGM_WIN6: "Victory – wireless / special battle"
};

export function friendlyMeta(name) {
  if (EXACT[name]) return { usage: EXACT[name][0], variant: EXACT[name][1] };
  if (WIN_NAMES[name]) return { usage: WIN_NAMES[name], variant: "" };

  const eye = name.match(/^SEQ_BGM_EYE_(\d+)$/);
  if (eye) return { usage: "Trainer notices you", variant: `Encounter group ${Number(eye[1])}` };
  if (name === "SEQ_BGM_EYE_PLASMA") return { usage: "Team Plasma notices you", variant: "" };

  const musicalDl = name.match(/^SEQ_BGM_MSL_DL_(\d+)$/);
  if (musicalDl) return { usage: "Pokémon Musical", variant: `Download jingle ${Number(musicalDl[1])}` };

  if (name.startsWith("SEQ_ME_")) {
    const me = {
      SEQ_ME_ASA: "Short jingle – morning / start",
      SEQ_ME_LVUP: "Short jingle – level up",
      SEQ_ME_ITEM: "Short jingle – received item",
      SEQ_ME_KEYITEM: "Short jingle – received key item",
      SEQ_ME_POKEGET: "Short jingle – caught / received Pokémon",
      SEQ_ME_SHINKAOME: "Short jingle – evolution complete",
      SEQ_ME_BADGE: "Short jingle – received badge",
      SEQ_ME_WAZA: "Short jingle – learned move",
      SEQ_ME_ACCE: "Short jingle – received accessory",
      SEQ_ME_WASURE: "Short jingle – move forgotten",
      SEQ_ME_KINOMI: "Short jingle – berry / item event"
    };
    return { usage: me[name] || "Short in-game jingle", variant: "" };
  }

  // Final fallback deliberately avoids using the internal identifier as the folder name.
  return { usage: "Other in-game music", variant: `Sequence ${name.replace(/^SEQ_(BGM|ME)_/, "").replaceAll("_", " ").toLowerCase()}` };
}

